# Code generated by `ubx sdk gen` from kubernetes_core_node. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Node_Items_Metadata_ManagedFields:
    api_version: Any = None
    fields_type: Any = None
    fields_v1: Any = None
    manager: Any = None
    operation: Any = None
    subresource: Any = None
    time: Any = None

@dataclasses.dataclass
class Node_Items_Metadata_OwnerReferences:
    api_version: Any = None
    block_owner_deletion: Any = None
    controller: Any = None
    kind: Any = None
    name: Any = None
    uid: Any = None

@dataclasses.dataclass
class Node_Items_Metadata:
    annotations: Any = None
    creation_timestamp: Any = None
    deletion_grace_period_seconds: Any = None
    deletion_timestamp: Any = None
    finalizers: Any = None
    generate_name: Any = None
    generation: Any = None
    labels: Any = None
    managed_fields: Any = None
    name: Any = None
    namespace: Any = None
    owner_references: Any = None
    resource_version: Any = None
    self_link: Any = None
    uid: Any = None

@dataclasses.dataclass
class Node_Items_Spec_ConfigSource_ConfigMap:
    kubelet_config_key: Any = None
    name: Any = None
    namespace: Any = None
    resource_version: Any = None
    uid: Any = None

@dataclasses.dataclass
class Node_Items_Spec_ConfigSource:
    config_map: Any = None

@dataclasses.dataclass
class Node_Items_Spec_PodPreemptionPolicy:
    disable_resize_preemption: Any = None

@dataclasses.dataclass
class Node_Items_Spec_Taints:
    effect: Any = None
    key: Any = None
    time_added: Any = None
    value: Any = None

@dataclasses.dataclass
class Node_Items_Spec:
    config_source: Any = None
    external_id: Any = None
    pod_cidr: Any = None
    pod_cidrs: Any = None
    pod_preemption_policy: Any = None
    provider_id: Any = None
    taints: Any = None
    unschedulable: Any = None

@dataclasses.dataclass
class Node_Items_Status_Addresses:
    address: Any = None
    type: Any = None

@dataclasses.dataclass
class Node_Items_Status_Conditions:
    last_heartbeat_time: Any = None
    last_transition_time: Any = None
    message: Any = None
    reason: Any = None
    status: Any = None
    type: Any = None

@dataclasses.dataclass
class Node_Items_Status_Config:
    active: Any = None
    assigned: Any = None
    error: Any = None
    last_known_good: Any = None

@dataclasses.dataclass
class Node_Items_Status_DaemonEndpoints_KubeletEndpoint:
    port: Any = None

@dataclasses.dataclass
class Node_Items_Status_DaemonEndpoints:
    kubelet_endpoint: Any = None

@dataclasses.dataclass
class Node_Items_Status_Features:
    supplemental_groups_policy: Any = None

@dataclasses.dataclass
class Node_Items_Status_Images:
    names: Any = None
    size_bytes: Any = None

@dataclasses.dataclass
class Node_Items_Status_NodeInfo_Swap:
    capacity: Any = None

@dataclasses.dataclass
class Node_Items_Status_NodeInfo:
    architecture: Any = None
    boot_id: Any = None
    container_runtime_version: Any = None
    kernel_version: Any = None
    kube_proxy_version: Any = None
    kubelet_version: Any = None
    machine_id: Any = None
    operating_system: Any = None
    os_image: Any = None
    running_in_user_namespace: Any = None
    swap: Any = None
    system_uuid: Any = None

@dataclasses.dataclass
class Node_Items_Status_RuntimeHandlers_Features:
    recursive_read_only_mounts: Any = None
    user_namespaces: Any = None

@dataclasses.dataclass
class Node_Items_Status_RuntimeHandlers:
    features: Any = None
    name: Any = None

@dataclasses.dataclass
class Node_Items_Status_VolumesAttached:
    device_path: Any = None
    name: Any = None

@dataclasses.dataclass
class Node_Items_Status:
    addresses: Any = None
    allocatable: Any = None
    capacity: Any = None
    conditions: Any = None
    config: Any = None
    daemon_endpoints: Any = None
    declared_features: Any = None
    features: Any = None
    images: Any = None
    node_info: Any = None
    phase: Any = None
    runtime_handlers: Any = None
    volumes_attached: Any = None
    volumes_in_use: Any = None

@dataclasses.dataclass
class Node_Items:
    api_version: Any = None
    kind: Any = None
    metadata: Any = None
    spec: Any = None
    status: Any = None

@dataclasses.dataclass
class Node_Metadata_ShardInfo:
    # selector is the shard selector string from the request, echoed back so clients can verify which shard they received and merge responses from multiple shards.
    selector: Any = None

@dataclasses.dataclass
class Node_Metadata:
    # continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message.
    continue_: Any = None
    # remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact.
    remaining_item_count: Any = None
    # String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
    resource_version: Any = None
    # Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
    self_link: Any = None
    # ShardInfo describes the shard selector that was applied to produce a list response. Its presence on a list response indicates the list is a filtered subset.
    shard_info: Any = None

@dataclasses.dataclass
class NodeConfig:
    allow_watch_bookmarks: Any = None
    continue_: Any = None
    field_selector: Any = None
    label_selector: Any = None
    limit: Any = None
    resource_version: Any = None
    resource_version_match: Any = None
    send_initial_events: Any = None
    shard_selector: Any = None
    timeout_seconds: Any = None
    watch: Any = None

@dataclasses.dataclass
class NodeAttrs:
    allow_watch_bookmarks: Any = None
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    continue_: Any = None
    field_selector: Any = None
    # List of nodes
    items: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    label_selector: Any = None
    limit: Any = None
    # ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
    metadata: Any = None
    resource_version: Any = None
    resource_version_match: Any = None
    send_initial_events: Any = None
    shard_selector: Any = None
    timeout_seconds: Any = None
    watch: Any = None

Node = ubx.DataSourceBinding(
    wire_type="kubernetes_core_node",
    fields={
        "allow_watch_bookmarks": ubx.FieldSpec(wire_name="allow_watch_bookmarks"),
        "continue_": ubx.FieldSpec(wire_name="continue"),
        "field_selector": ubx.FieldSpec(wire_name="field_selector"),
        "label_selector": ubx.FieldSpec(wire_name="label_selector"),
        "limit": ubx.FieldSpec(wire_name="limit"),
        "resource_version": ubx.FieldSpec(wire_name="resource_version"),
        "resource_version_match": ubx.FieldSpec(wire_name="resource_version_match"),
        "send_initial_events": ubx.FieldSpec(wire_name="send_initial_events"),
        "shard_selector": ubx.FieldSpec(wire_name="shard_selector"),
        "timeout_seconds": ubx.FieldSpec(wire_name="timeout_seconds"),
        "watch": ubx.FieldSpec(wire_name="watch"),
    },
)
