// Code generated by `ubx sdk gen` from kubernetes_core_replication_controller_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ReplicationControllerList_Items_Metadata_ManagedFields {
  apiVersion?: string | Computed<string>;
  fieldsType?: string | Computed<string>;
  fieldsV1?: unknown | Computed<unknown>;
  manager?: string | Computed<string>;
  operation?: string | Computed<string>;
  subresource?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Metadata_OwnerReferences {
  apiVersion?: string | Computed<string>;
  blockOwnerDeletion?: boolean | Computed<boolean>;
  controller?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Metadata {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  creationTimestamp?: string | Computed<string>;
  deletionGracePeriodSeconds?: number | Computed<number>;
  deletionTimestamp?: string | Computed<string>;
  finalizers?: string[] | Computed<string[]>;
  generateName?: string | Computed<string>;
  generation?: number | Computed<number>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  managedFields?: ReplicationControllerList_Items_Metadata_ManagedFields[] | Computed<ReplicationControllerList_Items_Metadata_ManagedFields[]>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  ownerReferences?: ReplicationControllerList_Items_Metadata_OwnerReferences[] | Computed<ReplicationControllerList_Items_Metadata_OwnerReferences[]>;
  resourceVersion?: string | Computed<string>;
  selfLink?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions {
  key?: string | Computed<string>;
  operator?: string | Computed<string>;
  values?: string[] | Computed<string[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference {
  matchExpressions?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[]>;
  matchFields?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  preference?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference>;
  weight?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution {
  nodeSelectorTerms?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity {
  preferredDuringSchedulingIgnoredDuringExecution?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution[]>;
  requiredDuringSchedulingIgnoredDuringExecution?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector {
  matchExpressions?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference_MatchExpressions[]>;
  matchLabels?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm {
  labelSelector?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector>;
  matchLabelKeys?: string[] | Computed<string[]>;
  mismatchLabelKeys?: string[] | Computed<string[]>;
  namespaceSelector?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector>;
  namespaces?: string[] | Computed<string[]>;
  topologyKey?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  podAffinityTerm?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm>;
  weight?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity {
  preferredDuringSchedulingIgnoredDuringExecution?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution[]>;
  requiredDuringSchedulingIgnoredDuringExecution?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Affinity {
  nodeAffinity?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_NodeAffinity>;
  podAffinity?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity>;
  podAntiAffinity?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef {
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef {
  apiVersion?: string | Computed<string>;
  fieldPath?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef {
  key?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
  path?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef {
  containerName?: string | Computed<string>;
  divisor?: string | Computed<string>;
  resource?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom {
  configMapKeyRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef>;
  fieldRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef>;
  fileKeyRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef>;
  resourceFieldRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef>;
  secretKeyRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
  valueFrom?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef {
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom {
  configMapRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef>;
  prefix?: string | Computed<string>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec {
  command?: string[] | Computed<string[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet {
  host?: string | Computed<string>;
  httpHeaders?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  path?: string | Computed<string>;
  port?: string | Computed<string>;
  protocol?: string | Computed<string>;
  scheme?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep {
  seconds?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket {
  host?: string | Computed<string>;
  port?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart {
  exec?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec>;
  httpGet?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet>;
  sleep?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep>;
  tcpSocket?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle {
  postStart?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart>;
  preStop?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart>;
  stopSignal?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc {
  mode?: string | Computed<string>;
  port?: number | Computed<number>;
  service?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe {
  exec?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec>;
  failureThreshold?: number | Computed<number>;
  grpc?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc>;
  httpGet?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet>;
  initialDelaySeconds?: number | Computed<number>;
  periodSeconds?: number | Computed<number>;
  successThreshold?: number | Computed<number>;
  tcpSocket?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket>;
  terminationGracePeriodSeconds?: number | Computed<number>;
  timeoutSeconds?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Ports {
  containerPort?: number | Computed<number>;
  hostIp?: string | Computed<string>;
  hostPort?: number | Computed<number>;
  name?: string | Computed<string>;
  protocol?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_ResizePolicy {
  resourceName?: string | Computed<string>;
  restartPolicy?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources_Claims {
  name?: string | Computed<string>;
  request?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources {
  claims?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources_Claims[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources_Claims[]>;
  limits?: Record<string, string> | Computed<Record<string, string>>;
  requests?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes {
  operator?: string | Computed<string>;
  values?: number[] | Computed<number[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules {
  action?: string | Computed<string>;
  exitCodes?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile {
  localhostProfile?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities {
  add?: string[] | Computed<string[]>;
  drop?: string[] | Computed<string[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions {
  level?: string | Computed<string>;
  role?: string | Computed<string>;
  type?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions {
  gmsaCredentialSpec?: string | Computed<string>;
  gmsaCredentialSpecName?: string | Computed<string>;
  hostProcess?: boolean | Computed<boolean>;
  runAsUserName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext {
  allowPrivilegeEscalation?: boolean | Computed<boolean>;
  appArmorProfile?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  capabilities?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities>;
  privileged?: boolean | Computed<boolean>;
  procMount?: string | Computed<string>;
  readOnlyRootFilesystem?: boolean | Computed<boolean>;
  runAsGroup?: number | Computed<number>;
  runAsNonRoot?: boolean | Computed<boolean>;
  runAsUser?: number | Computed<number>;
  seLinuxOptions?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions>;
  seccompProfile?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  windowsOptions?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeDevices {
  devicePath?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeMounts {
  bindMountOptions?: string[] | Computed<string[]>;
  mountPath?: string | Computed<string>;
  mountPropagation?: string | Computed<string>;
  name?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  recursiveReadOnly?: string | Computed<string>;
  subPath?: string | Computed<string>;
  subPathExpr?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Containers {
  args?: string[] | Computed<string[]>;
  command?: string[] | Computed<string[]>;
  env?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env[]>;
  envFrom?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom[]>;
  image?: string | Computed<string>;
  imagePullPolicy?: string | Computed<string>;
  lifecycle?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle>;
  livenessProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  name?: string | Computed<string>;
  ports?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Ports[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Ports[]>;
  readinessProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  resizePolicy?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_ResizePolicy[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_ResizePolicy[]>;
  resources?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  restartPolicyRules?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[]>;
  securityContext?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext>;
  startupProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  stdin?: boolean | Computed<boolean>;
  stdinOnce?: boolean | Computed<boolean>;
  terminationMessagePath?: string | Computed<string>;
  terminationMessagePolicy?: string | Computed<string>;
  tty?: boolean | Computed<boolean>;
  volumeDevices?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeDevices[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeDevices[]>;
  volumeMounts?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeMounts[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeMounts[]>;
  workingDir?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_DnsConfig {
  nameservers?: string[] | Computed<string[]>;
  options?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  searches?: string[] | Computed<string[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_EphemeralContainers {
  args?: string[] | Computed<string[]>;
  command?: string[] | Computed<string[]>;
  env?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env[]>;
  envFrom?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_EnvFrom[]>;
  image?: string | Computed<string>;
  imagePullPolicy?: string | Computed<string>;
  lifecycle?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle>;
  livenessProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  name?: string | Computed<string>;
  ports?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Ports[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Ports[]>;
  readinessProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  resizePolicy?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_ResizePolicy[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_ResizePolicy[]>;
  resources?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  restartPolicyRules?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[]>;
  securityContext?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext>;
  startupProbe?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  stdin?: boolean | Computed<boolean>;
  stdinOnce?: boolean | Computed<boolean>;
  targetContainerName?: string | Computed<string>;
  terminationMessagePath?: string | Computed<string>;
  terminationMessagePolicy?: string | Computed<string>;
  tty?: boolean | Computed<boolean>;
  volumeDevices?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeDevices[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeDevices[]>;
  volumeMounts?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeMounts[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_VolumeMounts[]>;
  workingDir?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_EvictionResponders {
  name?: string | Computed<string>;
  priority?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_HostAliases {
  hostnames?: string[] | Computed<string[]>;
  ip?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets {
  name?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_ReadinessGates {
  conditionType?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_ResourceClaims {
  name?: string | Computed<string>;
  resourceClaimName?: string | Computed<string>;
  resourceClaimTemplateName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_SchedulingGroup {
  podGroupName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_SecurityContext {
  appArmorProfile?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  fsGroup?: number | Computed<number>;
  fsGroupChangePolicy?: string | Computed<string>;
  runAsGroup?: number | Computed<number>;
  runAsNonRoot?: boolean | Computed<boolean>;
  runAsUser?: number | Computed<number>;
  seLinuxChangePolicy?: string | Computed<string>;
  seLinuxOptions?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions>;
  seccompProfile?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  supplementalGroups?: number[] | Computed<number[]>;
  supplementalGroupsPolicy?: string | Computed<string>;
  sysctls?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  windowsOptions?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Tolerations {
  effect?: string | Computed<string>;
  key?: string | Computed<string>;
  operator?: string | Computed<string>;
  tolerationSeconds?: number | Computed<number>;
  value?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_TopologySpreadConstraints {
  labelSelector?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector>;
  matchLabelKeys?: string[] | Computed<string[]>;
  maxSkew?: number | Computed<number>;
  minDomains?: number | Computed<number>;
  nodeAffinityPolicy?: string | Computed<string>;
  nodeTaintsPolicy?: string | Computed<string>;
  topologyKey?: string | Computed<string>;
  whenUnsatisfiable?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore {
  fsType?: string | Computed<string>;
  partition?: number | Computed<number>;
  readOnly?: boolean | Computed<boolean>;
  volumeId?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureDisk {
  cachingMode?: string | Computed<string>;
  diskName?: string | Computed<string>;
  diskUri?: string | Computed<string>;
  fsType?: string | Computed<string>;
  kind?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureFile {
  readOnly?: boolean | Computed<boolean>;
  secretName?: string | Computed<string>;
  shareName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cephfs {
  monitors?: string[] | Computed<string[]>;
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretFile?: string | Computed<string>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  user?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cinder {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  volumeId?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items {
  key?: string | Computed<string>;
  mode?: number | Computed<number>;
  path?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Csi {
  driver?: string | Computed<string>;
  fsType?: string | Computed<string>;
  nodePublishSecretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  readOnly?: boolean | Computed<boolean>;
  volumeAttributes?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items {
  fieldRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef>;
  mode?: number | Computed<number>;
  path?: string | Computed<string>;
  resourceFieldRef?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef>;
  user?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_EmptyDir {
  medium?: string | Computed<string>;
  mode?: number | Computed<number>;
  sizeLimit?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource {
  apiGroup?: string | Computed<string>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef {
  apiGroup?: string | Computed<string>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources {
  limits?: Record<string, string> | Computed<Record<string, string>>;
  requests?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec {
  accessModes?: string[] | Computed<string[]>;
  dataSource?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource>;
  dataSourceRef?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef>;
  resources?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources>;
  selector?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector>;
  storageClassName?: string | Computed<string>;
  volumeAttributesClassName?: string | Computed<string>;
  volumeMode?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate {
  metadata?: ReplicationControllerList_Items_Metadata | Computed<ReplicationControllerList_Items_Metadata>;
  spec?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral {
  volumeClaimTemplate?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Fc {
  fsType?: string | Computed<string>;
  lun?: number | Computed<number>;
  readOnly?: boolean | Computed<boolean>;
  targetWwns?: string[] | Computed<string[]>;
  wwids?: string[] | Computed<string[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_FlexVolume {
  driver?: string | Computed<string>;
  fsType?: string | Computed<string>;
  options?: Record<string, string> | Computed<Record<string, string>>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Flocker {
  datasetName?: string | Computed<string>;
  datasetUuid?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk {
  fsType?: string | Computed<string>;
  partition?: number | Computed<number>;
  pdName?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GitRepo {
  directory?: string | Computed<string>;
  repository?: string | Computed<string>;
  revision?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Glusterfs {
  endpoints?: string | Computed<string>;
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_HostPath {
  path?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Image {
  pullPolicy?: string | Computed<string>;
  reference?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Iscsi {
  chapAuthDiscovery?: boolean | Computed<boolean>;
  chapAuthSession?: boolean | Computed<boolean>;
  fsType?: string | Computed<string>;
  initiatorName?: string | Computed<string>;
  iqn?: string | Computed<string>;
  iscsiInterface?: string | Computed<string>;
  lun?: number | Computed<number>;
  portals?: string[] | Computed<string[]>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  targetPortal?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Nfs {
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  server?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim {
  claimName?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk {
  fsType?: string | Computed<string>;
  pdId?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PortworxVolume {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  volumeId?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle {
  labelSelector?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm_LabelSelector>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
  path?: string | Computed<string>;
  signerName?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap {
  items?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi {
  items?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate {
  certificateChainPath?: string | Computed<string>;
  credentialBundlePath?: string | Computed<string>;
  keyPath?: string | Computed<string>;
  keyType?: string | Computed<string>;
  maxExpirationSeconds?: number | Computed<number>;
  signerName?: string | Computed<string>;
  user?: number | Computed<number>;
  userAnnotations?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken {
  audience?: string | Computed<string>;
  expirationSeconds?: number | Computed<number>;
  path?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources {
  clusterTrustBundle?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle>;
  configMap?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap>;
  downwardApi?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi>;
  podCertificate?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate>;
  secret?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap>;
  serviceAccountToken?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  sources?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected_Sources[]>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Quobyte {
  group?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  registry?: string | Computed<string>;
  tenant?: string | Computed<string>;
  user?: string | Computed<string>;
  volume?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Rbd {
  fsType?: string | Computed<string>;
  image?: string | Computed<string>;
  keyring?: string | Computed<string>;
  monitors?: string[] | Computed<string[]>;
  pool?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  user?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ScaleIo {
  fsType?: string | Computed<string>;
  gateway?: string | Computed<string>;
  protectionDomain?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  sslEnabled?: boolean | Computed<boolean>;
  storageMode?: string | Computed<string>;
  storagePool?: string | Computed<string>;
  system?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Secret {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  optional?: boolean | Computed<boolean>;
  secretName?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Storageos {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  volumeName?: string | Computed<string>;
  volumeNamespace?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes_VsphereVolume {
  fsType?: string | Computed<string>;
  storagePolicyId?: string | Computed<string>;
  storagePolicyName?: string | Computed<string>;
  volumePath?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec_Volumes {
  awsElasticBlockStore?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore>;
  azureDisk?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureDisk | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureDisk>;
  azureFile?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureFile | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_AzureFile>;
  cephfs?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cephfs | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cephfs>;
  cinder?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cinder | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Cinder>;
  configMap?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ConfigMap>;
  csi?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Csi | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Csi>;
  downwardApi?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_DownwardApi>;
  emptyDir?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_EmptyDir | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_EmptyDir>;
  ephemeral?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Ephemeral>;
  fc?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Fc | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Fc>;
  flexVolume?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_FlexVolume | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_FlexVolume>;
  flocker?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Flocker | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Flocker>;
  gcePersistentDisk?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk>;
  gitRepo?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GitRepo | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_GitRepo>;
  glusterfs?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Glusterfs | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Glusterfs>;
  hostPath?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_HostPath | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_HostPath>;
  image?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Image | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Image>;
  iscsi?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Iscsi | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Iscsi>;
  name?: string | Computed<string>;
  nfs?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Nfs | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Nfs>;
  persistentVolumeClaim?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim>;
  photonPersistentDisk?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk>;
  portworxVolume?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PortworxVolume | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_PortworxVolume>;
  projected?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Projected>;
  quobyte?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Quobyte | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Quobyte>;
  rbd?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Rbd | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Rbd>;
  scaleIo?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ScaleIo | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_ScaleIo>;
  secret?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Secret | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Secret>;
  storageos?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Storageos | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_Storageos>;
  vsphereVolume?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes_VsphereVolume | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes_VsphereVolume>;
}

export interface ReplicationControllerList_Items_Spec_Template_Spec {
  activeDeadlineSeconds?: number | Computed<number>;
  affinity?: ReplicationControllerList_Items_Spec_Template_Spec_Affinity | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Affinity>;
  automountServiceAccountToken?: boolean | Computed<boolean>;
  containers?: ReplicationControllerList_Items_Spec_Template_Spec_Containers[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers[]>;
  dnsConfig?: ReplicationControllerList_Items_Spec_Template_Spec_DnsConfig | Computed<ReplicationControllerList_Items_Spec_Template_Spec_DnsConfig>;
  dnsPolicy?: string | Computed<string>;
  enableServiceLinks?: boolean | Computed<boolean>;
  ephemeralContainers?: ReplicationControllerList_Items_Spec_Template_Spec_EphemeralContainers[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_EphemeralContainers[]>;
  evictionResponders?: ReplicationControllerList_Items_Spec_Template_Spec_EvictionResponders[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_EvictionResponders[]>;
  hostAliases?: ReplicationControllerList_Items_Spec_Template_Spec_HostAliases[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_HostAliases[]>;
  hostIpc?: boolean | Computed<boolean>;
  hostNetwork?: boolean | Computed<boolean>;
  hostPid?: boolean | Computed<boolean>;
  hostUsers?: boolean | Computed<boolean>;
  hostname?: string | Computed<string>;
  hostnameOverride?: string | Computed<string>;
  imagePullSecrets?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets[]>;
  initContainers?: ReplicationControllerList_Items_Spec_Template_Spec_Containers[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers[]>;
  nodeName?: string | Computed<string>;
  nodeSelector?: Record<string, string> | Computed<Record<string, string>>;
  os?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets>;
  overhead?: Record<string, string> | Computed<Record<string, string>>;
  preemptionPolicy?: string | Computed<string>;
  priority?: number | Computed<number>;
  priorityClassName?: string | Computed<string>;
  readinessGates?: ReplicationControllerList_Items_Spec_Template_Spec_ReadinessGates[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ReadinessGates[]>;
  resourceClaims?: ReplicationControllerList_Items_Spec_Template_Spec_ResourceClaims[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ResourceClaims[]>;
  resources?: ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  runtimeClassName?: string | Computed<string>;
  schedulerName?: string | Computed<string>;
  schedulingGates?: ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_ImagePullSecrets[]>;
  schedulingGroup?: ReplicationControllerList_Items_Spec_Template_Spec_SchedulingGroup | Computed<ReplicationControllerList_Items_Spec_Template_Spec_SchedulingGroup>;
  securityContext?: ReplicationControllerList_Items_Spec_Template_Spec_SecurityContext | Computed<ReplicationControllerList_Items_Spec_Template_Spec_SecurityContext>;
  serviceAccount?: string | Computed<string>;
  serviceAccountName?: string | Computed<string>;
  setHostnameAsFqdn?: boolean | Computed<boolean>;
  shareProcessNamespace?: boolean | Computed<boolean>;
  subdomain?: string | Computed<string>;
  terminationGracePeriodSeconds?: number | Computed<number>;
  tolerations?: ReplicationControllerList_Items_Spec_Template_Spec_Tolerations[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Tolerations[]>;
  topologySpreadConstraints?: ReplicationControllerList_Items_Spec_Template_Spec_TopologySpreadConstraints[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_TopologySpreadConstraints[]>;
  volumes?: ReplicationControllerList_Items_Spec_Template_Spec_Volumes[] | Computed<ReplicationControllerList_Items_Spec_Template_Spec_Volumes[]>;
}

export interface ReplicationControllerList_Items_Spec_Template {
  metadata?: ReplicationControllerList_Items_Metadata | Computed<ReplicationControllerList_Items_Metadata>;
  spec?: ReplicationControllerList_Items_Spec_Template_Spec | Computed<ReplicationControllerList_Items_Spec_Template_Spec>;
}

export interface ReplicationControllerList_Items_Spec {
  minReadySeconds?: number | Computed<number>;
  replicas?: number | Computed<number>;
  selector?: Record<string, string> | Computed<Record<string, string>>;
  template?: ReplicationControllerList_Items_Spec_Template | Computed<ReplicationControllerList_Items_Spec_Template>;
}

export interface ReplicationControllerList_Items_Status_Conditions {
  lastTransitionTime?: string | Computed<string>;
  message?: string | Computed<string>;
  reason?: string | Computed<string>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicationControllerList_Items_Status {
  availableReplicas?: number | Computed<number>;
  conditions?: ReplicationControllerList_Items_Status_Conditions[] | Computed<ReplicationControllerList_Items_Status_Conditions[]>;
  fullyLabeledReplicas?: number | Computed<number>;
  observedGeneration?: number | Computed<number>;
  readyReplicas?: number | Computed<number>;
  replicas?: number | Computed<number>;
}

export interface ReplicationControllerList_Items {
  apiVersion?: string | Computed<string>;
  kind?: string | Computed<string>;
  metadata?: ReplicationControllerList_Items_Metadata | Computed<ReplicationControllerList_Items_Metadata>;
  spec?: ReplicationControllerList_Items_Spec | Computed<ReplicationControllerList_Items_Spec>;
  status?: ReplicationControllerList_Items_Status | Computed<ReplicationControllerList_Items_Status>;
}

export interface ReplicationControllerList_Metadata_ShardInfo {
  /** selector is the shard selector string from the request, echoed back so clients can verify which shard they received and merge responses from multiple shards. */
  selector: string | Computed<string>;
}

export interface ReplicationControllerList_Metadata {
  /** continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message. */
  continue?: string | Computed<string>;
  /** remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact. */
  remainingItemCount?: number | Computed<number>;
  /** String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency */
  resourceVersion?: string | Computed<string>;
  /** Deprecated: selfLink is a legacy read-only field that is no longer populated by the system. */
  selfLink?: string | Computed<string>;
  /** ShardInfo describes the shard selector that was applied to produce a list response. Its presence on a list response indicates the list is a filtered subset. */
  shardInfo?: ReplicationControllerList_Metadata_ShardInfo | Computed<ReplicationControllerList_Metadata_ShardInfo>;
}

export interface ReplicationControllerListConfig {
  allowWatchBookmarks?: boolean | Computed<boolean>;
  continue?: string | Computed<string>;
  fieldSelector?: string | Computed<string>;
  labelSelector?: string | Computed<string>;
  limit?: number | Computed<number>;
  resourceVersion?: string | Computed<string>;
  resourceVersionMatch?: string | Computed<string>;
  sendInitialEvents?: boolean | Computed<boolean>;
  shardSelector?: string | Computed<string>;
  timeoutSeconds?: number | Computed<number>;
  watch?: boolean | Computed<boolean>;
}

export interface ReplicationControllerListAttrs {
  allowWatchBookmarks: boolean;
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion: string;
  continue: string;
  fieldSelector: string;
  /** List of replication controllers. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller */
  items: ReplicationControllerList_Items[];
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind: string;
  labelSelector: string;
  limit: number;
  /** ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}. */
  metadata: ReplicationControllerList_Metadata;
  resourceVersion: string;
  resourceVersionMatch: string;
  sendInitialEvents: boolean;
  shardSelector: string;
  timeoutSeconds: number;
  watch: boolean;
}

export const ReplicationControllerList: DataSourceBinding<ReplicationControllerListConfig, ReplicationControllerListAttrs> = {
  wireType: "kubernetes_core_replication_controller_list",
  fields: {
    allowWatchBookmarks: "allow_watch_bookmarks",
    continue: "continue",
    fieldSelector: "field_selector",
    labelSelector: "label_selector",
    limit: "limit",
    resourceVersion: "resource_version",
    resourceVersionMatch: "resource_version_match",
    sendInitialEvents: "send_initial_events",
    shardSelector: "shard_selector",
    timeoutSeconds: "timeout_seconds",
    watch: "watch",
  },
};
