// Code generated by `ubx sdk gen` from kubernetes_apps_replica_set_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ReplicaSetList_Items_Metadata_ManagedFields {
  apiVersion?: string | Computed<string>;
  fieldsType?: string | Computed<string>;
  fieldsV1?: unknown | Computed<unknown>;
  manager?: string | Computed<string>;
  operation?: string | Computed<string>;
  subresource?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Metadata_OwnerReferences {
  apiVersion?: string | Computed<string>;
  blockOwnerDeletion?: boolean | Computed<boolean>;
  controller?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Metadata {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  creationTimestamp?: string | Computed<string>;
  deletionGracePeriodSeconds?: number | Computed<number>;
  deletionTimestamp?: string | Computed<string>;
  finalizers?: string[] | Computed<string[]>;
  generateName?: string | Computed<string>;
  generation?: number | Computed<number>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  managedFields?: ReplicaSetList_Items_Metadata_ManagedFields[] | Computed<ReplicaSetList_Items_Metadata_ManagedFields[]>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  ownerReferences?: ReplicaSetList_Items_Metadata_OwnerReferences[] | Computed<ReplicaSetList_Items_Metadata_OwnerReferences[]>;
  resourceVersion?: string | Computed<string>;
  selfLink?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Selector_MatchExpressions {
  key?: string | Computed<string>;
  operator?: string | Computed<string>;
  values?: string[] | Computed<string[]>;
}

export interface ReplicaSetList_Items_Spec_Selector {
  matchExpressions?: ReplicaSetList_Items_Spec_Selector_MatchExpressions[] | Computed<ReplicaSetList_Items_Spec_Selector_MatchExpressions[]>;
  matchLabels?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference {
  matchExpressions?: ReplicaSetList_Items_Spec_Selector_MatchExpressions[] | Computed<ReplicaSetList_Items_Spec_Selector_MatchExpressions[]>;
  matchFields?: ReplicaSetList_Items_Spec_Selector_MatchExpressions[] | Computed<ReplicaSetList_Items_Spec_Selector_MatchExpressions[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  preference?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference>;
  weight?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution {
  nodeSelectorTerms?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity {
  preferredDuringSchedulingIgnoredDuringExecution?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution[]>;
  requiredDuringSchedulingIgnoredDuringExecution?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm {
  labelSelector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  matchLabelKeys?: string[] | Computed<string[]>;
  mismatchLabelKeys?: string[] | Computed<string[]>;
  namespaceSelector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  namespaces?: string[] | Computed<string[]>;
  topologyKey?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  podAffinityTerm?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm>;
  weight?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity {
  preferredDuringSchedulingIgnoredDuringExecution?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution[]>;
  requiredDuringSchedulingIgnoredDuringExecution?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Affinity {
  nodeAffinity?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_NodeAffinity>;
  podAffinity?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity>;
  podAntiAffinity?: ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity_PodAffinity>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef {
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef {
  apiVersion?: string | Computed<string>;
  fieldPath?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef {
  key?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
  path?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef {
  containerName?: string | Computed<string>;
  divisor?: string | Computed<string>;
  resource?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom {
  configMapKeyRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef>;
  fieldRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef>;
  fileKeyRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FileKeyRef>;
  resourceFieldRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef>;
  secretKeyRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ConfigMapKeyRef>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Env {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
  valueFrom?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef {
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom {
  configMapRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef>;
  prefix?: string | Computed<string>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom_ConfigMapRef>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec {
  command?: string[] | Computed<string[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders {
  name?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet {
  host?: string | Computed<string>;
  httpHeaders?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  path?: string | Computed<string>;
  port?: string | Computed<string>;
  protocol?: string | Computed<string>;
  scheme?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep {
  seconds?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket {
  host?: string | Computed<string>;
  port?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart {
  exec?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec>;
  httpGet?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet>;
  sleep?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Sleep>;
  tcpSocket?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle {
  postStart?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart>;
  preStop?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart>;
  stopSignal?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc {
  mode?: string | Computed<string>;
  port?: number | Computed<number>;
  service?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe {
  exec?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_Exec>;
  failureThreshold?: number | Computed<number>;
  grpc?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe_Grpc>;
  httpGet?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet>;
  initialDelaySeconds?: number | Computed<number>;
  periodSeconds?: number | Computed<number>;
  successThreshold?: number | Computed<number>;
  tcpSocket?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_TcpSocket>;
  terminationGracePeriodSeconds?: number | Computed<number>;
  timeoutSeconds?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Ports {
  containerPort?: number | Computed<number>;
  hostIp?: string | Computed<string>;
  hostPort?: number | Computed<number>;
  name?: string | Computed<string>;
  protocol?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_ResizePolicy {
  resourceName?: string | Computed<string>;
  restartPolicy?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources_Claims {
  name?: string | Computed<string>;
  request?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources {
  claims?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources_Claims[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources_Claims[]>;
  limits?: Record<string, string> | Computed<Record<string, string>>;
  requests?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes {
  operator?: string | Computed<string>;
  values?: number[] | Computed<number[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules {
  action?: string | Computed<string>;
  exitCodes?: ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules_ExitCodes>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile {
  localhostProfile?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities {
  add?: string[] | Computed<string[]>;
  drop?: string[] | Computed<string[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions {
  level?: string | Computed<string>;
  role?: string | Computed<string>;
  type?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions {
  gmsaCredentialSpec?: string | Computed<string>;
  gmsaCredentialSpecName?: string | Computed<string>;
  hostProcess?: boolean | Computed<boolean>;
  runAsUserName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext {
  allowPrivilegeEscalation?: boolean | Computed<boolean>;
  appArmorProfile?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  capabilities?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_Capabilities>;
  privileged?: boolean | Computed<boolean>;
  procMount?: string | Computed<string>;
  readOnlyRootFilesystem?: boolean | Computed<boolean>;
  runAsGroup?: number | Computed<number>;
  runAsNonRoot?: boolean | Computed<boolean>;
  runAsUser?: number | Computed<number>;
  seLinuxOptions?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions>;
  seccompProfile?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  windowsOptions?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeDevices {
  devicePath?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeMounts {
  bindMountOptions?: string[] | Computed<string[]>;
  mountPath?: string | Computed<string>;
  mountPropagation?: string | Computed<string>;
  name?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  recursiveReadOnly?: string | Computed<string>;
  subPath?: string | Computed<string>;
  subPathExpr?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Containers {
  args?: string[] | Computed<string[]>;
  command?: string[] | Computed<string[]>;
  env?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env[]>;
  envFrom?: ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom[]>;
  image?: string | Computed<string>;
  imagePullPolicy?: string | Computed<string>;
  lifecycle?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle>;
  livenessProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  name?: string | Computed<string>;
  ports?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Ports[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Ports[]>;
  readinessProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  resizePolicy?: ReplicaSetList_Items_Spec_Template_Spec_Containers_ResizePolicy[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_ResizePolicy[]>;
  resources?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  restartPolicyRules?: ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[]>;
  securityContext?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext>;
  startupProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  stdin?: boolean | Computed<boolean>;
  stdinOnce?: boolean | Computed<boolean>;
  terminationMessagePath?: string | Computed<string>;
  terminationMessagePolicy?: string | Computed<string>;
  tty?: boolean | Computed<boolean>;
  volumeDevices?: ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeDevices[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeDevices[]>;
  volumeMounts?: ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeMounts[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeMounts[]>;
  workingDir?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_DnsConfig {
  nameservers?: string[] | Computed<string[]>;
  options?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  searches?: string[] | Computed<string[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_EphemeralContainers {
  args?: string[] | Computed<string[]>;
  command?: string[] | Computed<string[]>;
  env?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env[]>;
  envFrom?: ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_EnvFrom[]>;
  image?: string | Computed<string>;
  imagePullPolicy?: string | Computed<string>;
  lifecycle?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle>;
  livenessProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  name?: string | Computed<string>;
  ports?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Ports[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Ports[]>;
  readinessProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  resizePolicy?: ReplicaSetList_Items_Spec_Template_Spec_Containers_ResizePolicy[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_ResizePolicy[]>;
  resources?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  restartPolicyRules?: ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_RestartPolicyRules[]>;
  securityContext?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext>;
  startupProbe?: ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_LivenessProbe>;
  stdin?: boolean | Computed<boolean>;
  stdinOnce?: boolean | Computed<boolean>;
  targetContainerName?: string | Computed<string>;
  terminationMessagePath?: string | Computed<string>;
  terminationMessagePolicy?: string | Computed<string>;
  tty?: boolean | Computed<boolean>;
  volumeDevices?: ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeDevices[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeDevices[]>;
  volumeMounts?: ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeMounts[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_VolumeMounts[]>;
  workingDir?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_EvictionResponders {
  name?: string | Computed<string>;
  priority?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_HostAliases {
  hostnames?: string[] | Computed<string[]>;
  ip?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets {
  name?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_ReadinessGates {
  conditionType?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_ResourceClaims {
  name?: string | Computed<string>;
  resourceClaimName?: string | Computed<string>;
  resourceClaimTemplateName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_SchedulingGroup {
  podGroupName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_SecurityContext {
  appArmorProfile?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  fsGroup?: number | Computed<number>;
  fsGroupChangePolicy?: string | Computed<string>;
  runAsGroup?: number | Computed<number>;
  runAsNonRoot?: boolean | Computed<boolean>;
  runAsUser?: number | Computed<number>;
  seLinuxChangePolicy?: string | Computed<string>;
  seLinuxOptions?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_SeLinuxOptions>;
  seccompProfile?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_AppArmorProfile>;
  supplementalGroups?: number[] | Computed<number[]>;
  supplementalGroupsPolicy?: string | Computed<string>;
  sysctls?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Lifecycle_PostStart_HttpGet_HttpHeaders[]>;
  windowsOptions?: ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_SecurityContext_WindowsOptions>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Tolerations {
  effect?: string | Computed<string>;
  key?: string | Computed<string>;
  operator?: string | Computed<string>;
  tolerationSeconds?: number | Computed<number>;
  value?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_TopologySpreadConstraints {
  labelSelector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  matchLabelKeys?: string[] | Computed<string[]>;
  maxSkew?: number | Computed<number>;
  minDomains?: number | Computed<number>;
  nodeAffinityPolicy?: string | Computed<string>;
  nodeTaintsPolicy?: string | Computed<string>;
  topologyKey?: string | Computed<string>;
  whenUnsatisfiable?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore {
  fsType?: string | Computed<string>;
  partition?: number | Computed<number>;
  readOnly?: boolean | Computed<boolean>;
  volumeId?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureDisk {
  cachingMode?: string | Computed<string>;
  diskName?: string | Computed<string>;
  diskUri?: string | Computed<string>;
  fsType?: string | Computed<string>;
  kind?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureFile {
  readOnly?: boolean | Computed<boolean>;
  secretName?: string | Computed<string>;
  shareName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cephfs {
  monitors?: string[] | Computed<string[]>;
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretFile?: string | Computed<string>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  user?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cinder {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  volumeId?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items {
  key?: string | Computed<string>;
  mode?: number | Computed<number>;
  path?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Csi {
  driver?: string | Computed<string>;
  fsType?: string | Computed<string>;
  nodePublishSecretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  readOnly?: boolean | Computed<boolean>;
  volumeAttributes?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items {
  fieldRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_FieldRef>;
  mode?: number | Computed<number>;
  path?: string | Computed<string>;
  resourceFieldRef?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Env_ValueFrom_ResourceFieldRef>;
  user?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_EmptyDir {
  medium?: string | Computed<string>;
  mode?: number | Computed<number>;
  sizeLimit?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource {
  apiGroup?: string | Computed<string>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef {
  apiGroup?: string | Computed<string>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources {
  limits?: Record<string, string> | Computed<Record<string, string>>;
  requests?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec {
  accessModes?: string[] | Computed<string[]>;
  dataSource?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSource>;
  dataSourceRef?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_DataSourceRef>;
  resources?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec_Resources>;
  selector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  storageClassName?: string | Computed<string>;
  volumeAttributesClassName?: string | Computed<string>;
  volumeMode?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate {
  metadata?: ReplicaSetList_Items_Metadata | Computed<ReplicaSetList_Items_Metadata>;
  spec?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate_Spec>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral {
  volumeClaimTemplate?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral_VolumeClaimTemplate>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Fc {
  fsType?: string | Computed<string>;
  lun?: number | Computed<number>;
  readOnly?: boolean | Computed<boolean>;
  targetWwns?: string[] | Computed<string[]>;
  wwids?: string[] | Computed<string[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_FlexVolume {
  driver?: string | Computed<string>;
  fsType?: string | Computed<string>;
  options?: Record<string, string> | Computed<Record<string, string>>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Flocker {
  datasetName?: string | Computed<string>;
  datasetUuid?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk {
  fsType?: string | Computed<string>;
  partition?: number | Computed<number>;
  pdName?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_GitRepo {
  directory?: string | Computed<string>;
  repository?: string | Computed<string>;
  revision?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Glusterfs {
  endpoints?: string | Computed<string>;
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_HostPath {
  path?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Image {
  pullPolicy?: string | Computed<string>;
  reference?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Iscsi {
  chapAuthDiscovery?: boolean | Computed<boolean>;
  chapAuthSession?: boolean | Computed<boolean>;
  fsType?: string | Computed<string>;
  initiatorName?: string | Computed<string>;
  iqn?: string | Computed<string>;
  iscsiInterface?: string | Computed<string>;
  lun?: number | Computed<number>;
  portals?: string[] | Computed<string[]>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  targetPortal?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Nfs {
  path?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  server?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim {
  claimName?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk {
  fsType?: string | Computed<string>;
  pdId?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_PortworxVolume {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  volumeId?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle {
  labelSelector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
  path?: string | Computed<string>;
  signerName?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap {
  items?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  name?: string | Computed<string>;
  optional?: boolean | Computed<boolean>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi {
  items?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi_Items[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate {
  certificateChainPath?: string | Computed<string>;
  credentialBundlePath?: string | Computed<string>;
  keyPath?: string | Computed<string>;
  keyType?: string | Computed<string>;
  maxExpirationSeconds?: number | Computed<number>;
  signerName?: string | Computed<string>;
  user?: number | Computed<number>;
  userAnnotations?: Record<string, string> | Computed<Record<string, string>>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken {
  audience?: string | Computed<string>;
  expirationSeconds?: number | Computed<number>;
  path?: string | Computed<string>;
  user?: number | Computed<number>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources {
  clusterTrustBundle?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ClusterTrustBundle>;
  configMap?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap>;
  downwardApi?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_DownwardApi>;
  podCertificate?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_PodCertificate>;
  secret?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ConfigMap>;
  serviceAccountToken?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources_ServiceAccountToken>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  sources?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected_Sources[]>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Quobyte {
  group?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  registry?: string | Computed<string>;
  tenant?: string | Computed<string>;
  user?: string | Computed<string>;
  volume?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Rbd {
  fsType?: string | Computed<string>;
  image?: string | Computed<string>;
  keyring?: string | Computed<string>;
  monitors?: string[] | Computed<string[]>;
  pool?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  user?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_ScaleIo {
  fsType?: string | Computed<string>;
  gateway?: string | Computed<string>;
  protectionDomain?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  sslEnabled?: boolean | Computed<boolean>;
  storageMode?: string | Computed<string>;
  storagePool?: string | Computed<string>;
  system?: string | Computed<string>;
  volumeName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Secret {
  defaultMode?: number | Computed<number>;
  defaultUser?: number | Computed<number>;
  items?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap_Items[]>;
  optional?: boolean | Computed<boolean>;
  secretName?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_Storageos {
  fsType?: string | Computed<string>;
  readOnly?: boolean | Computed<boolean>;
  secretRef?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  volumeName?: string | Computed<string>;
  volumeNamespace?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes_VsphereVolume {
  fsType?: string | Computed<string>;
  storagePolicyId?: string | Computed<string>;
  storagePolicyName?: string | Computed<string>;
  volumePath?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec_Volumes {
  awsElasticBlockStore?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_AwsElasticBlockStore>;
  azureDisk?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureDisk | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureDisk>;
  azureFile?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureFile | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_AzureFile>;
  cephfs?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cephfs | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cephfs>;
  cinder?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cinder | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Cinder>;
  configMap?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_ConfigMap>;
  csi?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Csi | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Csi>;
  downwardApi?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_DownwardApi>;
  emptyDir?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_EmptyDir | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_EmptyDir>;
  ephemeral?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Ephemeral>;
  fc?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Fc | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Fc>;
  flexVolume?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_FlexVolume | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_FlexVolume>;
  flocker?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Flocker | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Flocker>;
  gcePersistentDisk?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_GcePersistentDisk>;
  gitRepo?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_GitRepo | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_GitRepo>;
  glusterfs?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Glusterfs | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Glusterfs>;
  hostPath?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_HostPath | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_HostPath>;
  image?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Image | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Image>;
  iscsi?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Iscsi | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Iscsi>;
  name?: string | Computed<string>;
  nfs?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Nfs | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Nfs>;
  persistentVolumeClaim?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_PersistentVolumeClaim>;
  photonPersistentDisk?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_PhotonPersistentDisk>;
  portworxVolume?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_PortworxVolume | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_PortworxVolume>;
  projected?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Projected>;
  quobyte?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Quobyte | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Quobyte>;
  rbd?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Rbd | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Rbd>;
  scaleIo?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_ScaleIo | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_ScaleIo>;
  secret?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Secret | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Secret>;
  storageos?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_Storageos | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_Storageos>;
  vsphereVolume?: ReplicaSetList_Items_Spec_Template_Spec_Volumes_VsphereVolume | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes_VsphereVolume>;
}

export interface ReplicaSetList_Items_Spec_Template_Spec {
  activeDeadlineSeconds?: number | Computed<number>;
  affinity?: ReplicaSetList_Items_Spec_Template_Spec_Affinity | Computed<ReplicaSetList_Items_Spec_Template_Spec_Affinity>;
  automountServiceAccountToken?: boolean | Computed<boolean>;
  containers?: ReplicaSetList_Items_Spec_Template_Spec_Containers[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers[]>;
  dnsConfig?: ReplicaSetList_Items_Spec_Template_Spec_DnsConfig | Computed<ReplicaSetList_Items_Spec_Template_Spec_DnsConfig>;
  dnsPolicy?: string | Computed<string>;
  enableServiceLinks?: boolean | Computed<boolean>;
  ephemeralContainers?: ReplicaSetList_Items_Spec_Template_Spec_EphemeralContainers[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_EphemeralContainers[]>;
  evictionResponders?: ReplicaSetList_Items_Spec_Template_Spec_EvictionResponders[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_EvictionResponders[]>;
  hostAliases?: ReplicaSetList_Items_Spec_Template_Spec_HostAliases[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_HostAliases[]>;
  hostIpc?: boolean | Computed<boolean>;
  hostNetwork?: boolean | Computed<boolean>;
  hostPid?: boolean | Computed<boolean>;
  hostUsers?: boolean | Computed<boolean>;
  hostname?: string | Computed<string>;
  hostnameOverride?: string | Computed<string>;
  imagePullSecrets?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets[]>;
  initContainers?: ReplicaSetList_Items_Spec_Template_Spec_Containers[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers[]>;
  nodeName?: string | Computed<string>;
  nodeSelector?: Record<string, string> | Computed<Record<string, string>>;
  os?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets>;
  overhead?: Record<string, string> | Computed<Record<string, string>>;
  preemptionPolicy?: string | Computed<string>;
  priority?: number | Computed<number>;
  priorityClassName?: string | Computed<string>;
  readinessGates?: ReplicaSetList_Items_Spec_Template_Spec_ReadinessGates[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_ReadinessGates[]>;
  resourceClaims?: ReplicaSetList_Items_Spec_Template_Spec_ResourceClaims[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_ResourceClaims[]>;
  resources?: ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources | Computed<ReplicaSetList_Items_Spec_Template_Spec_Containers_Resources>;
  restartPolicy?: string | Computed<string>;
  runtimeClassName?: string | Computed<string>;
  schedulerName?: string | Computed<string>;
  schedulingGates?: ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_ImagePullSecrets[]>;
  schedulingGroup?: ReplicaSetList_Items_Spec_Template_Spec_SchedulingGroup | Computed<ReplicaSetList_Items_Spec_Template_Spec_SchedulingGroup>;
  securityContext?: ReplicaSetList_Items_Spec_Template_Spec_SecurityContext | Computed<ReplicaSetList_Items_Spec_Template_Spec_SecurityContext>;
  serviceAccount?: string | Computed<string>;
  serviceAccountName?: string | Computed<string>;
  setHostnameAsFqdn?: boolean | Computed<boolean>;
  shareProcessNamespace?: boolean | Computed<boolean>;
  subdomain?: string | Computed<string>;
  terminationGracePeriodSeconds?: number | Computed<number>;
  tolerations?: ReplicaSetList_Items_Spec_Template_Spec_Tolerations[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Tolerations[]>;
  topologySpreadConstraints?: ReplicaSetList_Items_Spec_Template_Spec_TopologySpreadConstraints[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_TopologySpreadConstraints[]>;
  volumes?: ReplicaSetList_Items_Spec_Template_Spec_Volumes[] | Computed<ReplicaSetList_Items_Spec_Template_Spec_Volumes[]>;
}

export interface ReplicaSetList_Items_Spec_Template {
  metadata?: ReplicaSetList_Items_Metadata | Computed<ReplicaSetList_Items_Metadata>;
  spec?: ReplicaSetList_Items_Spec_Template_Spec | Computed<ReplicaSetList_Items_Spec_Template_Spec>;
}

export interface ReplicaSetList_Items_Spec {
  minReadySeconds?: number | Computed<number>;
  replicas?: number | Computed<number>;
  selector?: ReplicaSetList_Items_Spec_Selector | Computed<ReplicaSetList_Items_Spec_Selector>;
  template?: ReplicaSetList_Items_Spec_Template | Computed<ReplicaSetList_Items_Spec_Template>;
}

export interface ReplicaSetList_Items_Status_Conditions {
  lastTransitionTime?: string | Computed<string>;
  message?: string | Computed<string>;
  reason?: string | Computed<string>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ReplicaSetList_Items_Status {
  availableReplicas?: number | Computed<number>;
  conditions?: ReplicaSetList_Items_Status_Conditions[] | Computed<ReplicaSetList_Items_Status_Conditions[]>;
  fullyLabeledReplicas?: number | Computed<number>;
  observedGeneration?: number | Computed<number>;
  readyReplicas?: number | Computed<number>;
  replicas?: number | Computed<number>;
  terminatingReplicas?: number | Computed<number>;
}

export interface ReplicaSetList_Items {
  apiVersion?: string | Computed<string>;
  kind?: string | Computed<string>;
  metadata?: ReplicaSetList_Items_Metadata | Computed<ReplicaSetList_Items_Metadata>;
  spec?: ReplicaSetList_Items_Spec | Computed<ReplicaSetList_Items_Spec>;
  status?: ReplicaSetList_Items_Status | Computed<ReplicaSetList_Items_Status>;
}

export interface ReplicaSetList_Metadata_ShardInfo {
  /** selector is the shard selector string from the request, echoed back so clients can verify which shard they received and merge responses from multiple shards. */
  selector: string | Computed<string>;
}

export interface ReplicaSetList_Metadata {
  /** continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message. */
  continue?: string | Computed<string>;
  /** remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact. */
  remainingItemCount?: number | Computed<number>;
  /** String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency */
  resourceVersion?: string | Computed<string>;
  /** Deprecated: selfLink is a legacy read-only field that is no longer populated by the system. */
  selfLink?: string | Computed<string>;
  /** ShardInfo describes the shard selector that was applied to produce a list response. Its presence on a list response indicates the list is a filtered subset. */
  shardInfo?: ReplicaSetList_Metadata_ShardInfo | Computed<ReplicaSetList_Metadata_ShardInfo>;
}

export interface ReplicaSetListConfig {
  allowWatchBookmarks?: boolean | Computed<boolean>;
  continue?: string | Computed<string>;
  fieldSelector?: string | Computed<string>;
  labelSelector?: string | Computed<string>;
  limit?: number | Computed<number>;
  resourceVersion?: string | Computed<string>;
  resourceVersionMatch?: string | Computed<string>;
  sendInitialEvents?: boolean | Computed<boolean>;
  shardSelector?: string | Computed<string>;
  timeoutSeconds?: number | Computed<number>;
  watch?: boolean | Computed<boolean>;
}

export interface ReplicaSetListAttrs {
  allowWatchBookmarks: boolean;
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion: string;
  continue: string;
  fieldSelector: string;
  /** List of ReplicaSets. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset */
  items: ReplicaSetList_Items[];
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind: string;
  labelSelector: string;
  limit: number;
  /** ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}. */
  metadata: ReplicaSetList_Metadata;
  resourceVersion: string;
  resourceVersionMatch: string;
  sendInitialEvents: boolean;
  shardSelector: string;
  timeoutSeconds: number;
  watch: boolean;
}

export const ReplicaSetList: DataSourceBinding<ReplicaSetListConfig, ReplicaSetListAttrs> = {
  wireType: "kubernetes_apps_replica_set_list",
  fields: {
    allowWatchBookmarks: "allow_watch_bookmarks",
    continue: "continue",
    fieldSelector: "field_selector",
    labelSelector: "label_selector",
    limit: "limit",
    resourceVersion: "resource_version",
    resourceVersionMatch: "resource_version_match",
    sendInitialEvents: "send_initial_events",
    shardSelector: "shard_selector",
    timeoutSeconds: "timeout_seconds",
    watch: "watch",
  },
};
