// Code generated by `ubx sdk gen` from kubernetes_service_account. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Account_ImagePullSecret {
  name: string;
}

export interface Account_Metadata {
  annotations: Record<string, string>;
  generateName: string;
  generation: number;
  labels: Record<string, string>;
  name: string;
  namespace: string;
  resourceVersion: string;
  uid: string;
}

export interface Account_Timeouts {
  create: string;
}

const Account_ImagePullSecretFields: FieldMap = {
  name: "name",
};

const Account_MetadataFields: FieldMap = {
  annotations: "annotations",
  generateName: "generate_name",
  generation: "generation",
  labels: "labels",
  name: "name",
  namespace: "namespace",
  resourceVersion: "resource_version",
  uid: "uid",
};

const Account_TimeoutsFields: FieldMap = {
  create: "create",
};

export interface AccountConfig {
  automountServiceAccountToken?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  imagePullSecret?: Account_ImagePullSecret[] | Computed<Account_ImagePullSecret[]>;
  metadata?: Account_Metadata[] | Computed<Account_Metadata[]>;
  secret?: Account_ImagePullSecret[] | Computed<Account_ImagePullSecret[]>;
  timeouts?: Account_Timeouts | Computed<Account_Timeouts>;
}

export interface AccountAttrs {
  automountServiceAccountToken: boolean;
  defaultSecretName: string;
  id: string;
  imagePullSecret: Account_ImagePullSecret[];
  metadata: Account_Metadata[];
  secret: Account_ImagePullSecret[];
  timeouts: Account_Timeouts;
}

export const Account: ResourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "kubernetes_service_account",
  fields: {
    automountServiceAccountToken: "automount_service_account_token",
    id: "id",
    imagePullSecret: {
      wireName: "image_pull_secret",
      kind: "set",
      fields: Account_ImagePullSecretFields,
    },
    metadata: {
      wireName: "metadata",
      kind: "list",
      fields: Account_MetadataFields,
    },
    secret: {
      wireName: "secret",
      kind: "set",
      fields: Account_ImagePullSecretFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Account_TimeoutsFields,
    },
  },
};
