// Code generated by `ubx sdk gen` from kubernetes_discovery_endpoint_slice_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface EndpointSliceList_Items_Endpoints_Conditions {
  ready?: boolean | Computed<boolean>;
  serving?: boolean | Computed<boolean>;
  terminating?: boolean | Computed<boolean>;
}

export interface EndpointSliceList_Items_Endpoints_Hints_ForNodes {
  name?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Endpoints_Hints {
  forNodes?: EndpointSliceList_Items_Endpoints_Hints_ForNodes[] | Computed<EndpointSliceList_Items_Endpoints_Hints_ForNodes[]>;
  forZones?: EndpointSliceList_Items_Endpoints_Hints_ForNodes[] | Computed<EndpointSliceList_Items_Endpoints_Hints_ForNodes[]>;
}

export interface EndpointSliceList_Items_Endpoints_TargetRef {
  apiVersion?: string | Computed<string>;
  fieldPath?: string | Computed<string>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  resourceVersion?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Endpoints {
  addresses?: string[] | Computed<string[]>;
  conditions?: EndpointSliceList_Items_Endpoints_Conditions | Computed<EndpointSliceList_Items_Endpoints_Conditions>;
  deprecatedTopology?: Record<string, string> | Computed<Record<string, string>>;
  hints?: EndpointSliceList_Items_Endpoints_Hints | Computed<EndpointSliceList_Items_Endpoints_Hints>;
  hostname?: string | Computed<string>;
  nodeName?: string | Computed<string>;
  targetRef?: EndpointSliceList_Items_Endpoints_TargetRef | Computed<EndpointSliceList_Items_Endpoints_TargetRef>;
  zone?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Metadata_ManagedFields {
  apiVersion?: string | Computed<string>;
  fieldsType?: string | Computed<string>;
  fieldsV1?: unknown | Computed<unknown>;
  manager?: string | Computed<string>;
  operation?: string | Computed<string>;
  subresource?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Metadata_OwnerReferences {
  apiVersion?: string | Computed<string>;
  blockOwnerDeletion?: boolean | Computed<boolean>;
  controller?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Metadata {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  creationTimestamp?: string | Computed<string>;
  deletionGracePeriodSeconds?: number | Computed<number>;
  deletionTimestamp?: string | Computed<string>;
  finalizers?: string[] | Computed<string[]>;
  generateName?: string | Computed<string>;
  generation?: number | Computed<number>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  managedFields?: EndpointSliceList_Items_Metadata_ManagedFields[] | Computed<EndpointSliceList_Items_Metadata_ManagedFields[]>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  ownerReferences?: EndpointSliceList_Items_Metadata_OwnerReferences[] | Computed<EndpointSliceList_Items_Metadata_OwnerReferences[]>;
  resourceVersion?: string | Computed<string>;
  selfLink?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface EndpointSliceList_Items_Ports {
  appProtocol?: string | Computed<string>;
  name?: string | Computed<string>;
  port?: number | Computed<number>;
  protocol?: string | Computed<string>;
}

export interface EndpointSliceList_Items {
  addressType?: string | Computed<string>;
  apiVersion?: string | Computed<string>;
  endpoints?: EndpointSliceList_Items_Endpoints[] | Computed<EndpointSliceList_Items_Endpoints[]>;
  kind?: string | Computed<string>;
  metadata?: EndpointSliceList_Items_Metadata | Computed<EndpointSliceList_Items_Metadata>;
  ports?: EndpointSliceList_Items_Ports[] | Computed<EndpointSliceList_Items_Ports[]>;
}

export interface EndpointSliceList_Metadata_ShardInfo {
  /** selector is the shard selector string from the request, echoed back so clients can verify which shard they received and merge responses from multiple shards. */
  selector: string | Computed<string>;
}

export interface EndpointSliceList_Metadata {
  /** continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message. */
  continue?: string | Computed<string>;
  /** remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact. */
  remainingItemCount?: number | Computed<number>;
  /** String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency */
  resourceVersion?: string | Computed<string>;
  /** Deprecated: selfLink is a legacy read-only field that is no longer populated by the system. */
  selfLink?: string | Computed<string>;
  /** ShardInfo describes the shard selector that was applied to produce a list response. Its presence on a list response indicates the list is a filtered subset. */
  shardInfo?: EndpointSliceList_Metadata_ShardInfo | Computed<EndpointSliceList_Metadata_ShardInfo>;
}

export interface EndpointSliceListConfig {
}

export interface EndpointSliceListAttrs {
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion: string;
  /** items is the list of endpoint slices */
  items: EndpointSliceList_Items[];
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind: string;
  /** ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}. */
  metadata: EndpointSliceList_Metadata;
}

export const EndpointSliceList: DataSourceBinding<EndpointSliceListConfig, EndpointSliceListAttrs> = {
  wireType: "kubernetes_discovery_endpoint_slice_list",
  fields: {
  },
};
