// Code generated by `ubx sdk gen` from kubernetes_certificate_signing_request. DO NOT EDIT.
package certificate

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SigningRequest_Metadata struct {
	Annotations any
	GenerateName any
	Generation any
	Labels any
	Name any
	ResourceVersion any
	Uid any
}

type SigningRequest_Spec struct {
	Request any
	SignerName any
	Usages any
}

type SigningRequest_Timeouts struct {
	Create any
}

var SigningRequest_MetadataFields = ubx.FieldMap{
		"Annotations": ubx.FieldSpec{WireName: "annotations"},
		"GenerateName": ubx.FieldSpec{WireName: "generate_name"},
		"Generation": ubx.FieldSpec{WireName: "generation"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ResourceVersion": ubx.FieldSpec{WireName: "resource_version"},
		"Uid": ubx.FieldSpec{WireName: "uid"},
	}

var SigningRequest_SpecFields = ubx.FieldMap{
		"Request": ubx.FieldSpec{WireName: "request"},
		"SignerName": ubx.FieldSpec{WireName: "signer_name"},
		"Usages": ubx.FieldSpec{WireName: "usages"},
	}

var SigningRequest_TimeoutsFields = ubx.FieldMap{
		"Create": ubx.FieldSpec{WireName: "create"},
	}

type SigningRequestConfig struct {
	AutoApprove any
	Id any
	Metadata any
	Spec any
	Timeouts any
}

var SigningRequest = ubx.ResourceBinding{
	WireType: "kubernetes_certificate_signing_request",
	Fields: ubx.FieldMap{
		"AutoApprove": ubx.FieldSpec{WireName: "auto_approve"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"Metadata": ubx.FieldSpec{
			WireName: "metadata",
			Kind: "list",
			Fields: SigningRequest_MetadataFields,
		},
		"Spec": ubx.FieldSpec{
			WireName: "spec",
			Kind: "list",
			Fields: SigningRequest_SpecFields,
		},
		"Timeouts": ubx.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SigningRequest_TimeoutsFields,
		},
	},
}
