// Code generated by `ubx sdk gen` from kubernetes_role_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Binding_Metadata {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  generateName?: string | Computed<string>;
  generation?: number | Computed<number>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  resourceVersion?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface Binding_RoleRef {
  apiGroup: string | Computed<string>;
  kind: string | Computed<string>;
  name: string | Computed<string>;
}

export interface Binding_Subject {
  apiGroup?: string | Computed<string>;
  kind: string | Computed<string>;
  name: string | Computed<string>;
  namespace?: string | Computed<string>;
}

const Binding_MetadataFields: FieldMap = {
  annotations: "annotations",
  generateName: "generate_name",
  generation: "generation",
  labels: "labels",
  name: "name",
  namespace: "namespace",
  resourceVersion: "resource_version",
  uid: "uid",
};

const Binding_RoleRefFields: FieldMap = {
  apiGroup: "api_group",
  kind: "kind",
  name: "name",
};

const Binding_SubjectFields: FieldMap = {
  apiGroup: "api_group",
  kind: "kind",
  name: "name",
  namespace: "namespace",
};

export interface BindingConfig {
  id?: string | Computed<string>;
  metadata?: Binding_Metadata[] | Computed<Binding_Metadata[]>;
  roleRef?: Binding_RoleRef[] | Computed<Binding_RoleRef[]>;
  subject?: Binding_Subject[] | Computed<Binding_Subject[]>;
}

export interface BindingAttrs {
  id: string;
  metadata: Binding_Metadata[];
  roleRef: Binding_RoleRef[];
  subject: Binding_Subject[];
}

export const Binding: ResourceBinding<BindingConfig, BindingAttrs> = {
  wireType: "kubernetes_role_binding",
  fields: {
    id: "id",
    metadata: {
      wireName: "metadata",
      kind: "list",
      fields: Binding_MetadataFields,
    },
    roleRef: {
      wireName: "role_ref",
      kind: "list",
      fields: Binding_RoleRefFields,
    },
    subject: {
      wireName: "subject",
      kind: "list",
      fields: Binding_SubjectFields,
    },
  },
};
