// Code generated by `ubx sdk gen` from kubernetes_storagemigration_v1beta1_storage_version_migration. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface V1beta1StorageVersionMigration_Metadata_ManagedFields {
  apiVersion?: string | Computed<string>;
  fieldsType?: string | Computed<string>;
  fieldsV1?: unknown | Computed<unknown>;
  manager?: string | Computed<string>;
  operation?: string | Computed<string>;
  subresource?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface V1beta1StorageVersionMigration_Metadata_OwnerReferences {
  apiVersion?: string | Computed<string>;
  blockOwnerDeletion?: boolean | Computed<boolean>;
  controller?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface V1beta1StorageVersionMigration_Metadata {
  /** Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations */
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  /** Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers. */
  creationTimestamp?: string | Computed<string>;
  /** Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only. */
  deletionGracePeriodSeconds?: number | Computed<number>;
  /** Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers. */
  deletionTimestamp?: string | Computed<string>;
  /** Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list. */
  finalizers?: string[] | Computed<string[]>;
  /** GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency */
  generateName?: string | Computed<string>;
  /** A sequence number representing a specific generation of the desired state. Populated by the system. Read-only. */
  generation?: number | Computed<number>;
  /** Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object. */
  managedFields?: V1beta1StorageVersionMigration_Metadata_ManagedFields[] | Computed<V1beta1StorageVersionMigration_Metadata_ManagedFields[]>;
  /** Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
  name?: string | Computed<string>;
  /** Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
  namespace?: string | Computed<string>;
  /** List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller. */
  ownerReferences?: V1beta1StorageVersionMigration_Metadata_OwnerReferences[] | Computed<V1beta1StorageVersionMigration_Metadata_OwnerReferences[]>;
  /** An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency */
  resourceVersion?: string | Computed<string>;
  /** Deprecated: selfLink is a legacy read-only field that is no longer populated by the system. */
  selfLink?: string | Computed<string>;
  /** UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids */
  uid?: string | Computed<string>;
}

export interface V1beta1StorageVersionMigration_Spec_Resource {
  group: string | Computed<string>;
  resource: string | Computed<string>;
}

export interface V1beta1StorageVersionMigration_Spec {
  /** GroupResource specifies a Group and a Resource, but does not force a version. This is useful for identifying concepts during lookup stages without having partially valid types */
  resource: V1beta1StorageVersionMigration_Spec_Resource | Computed<V1beta1StorageVersionMigration_Spec_Resource>;
}

export interface V1beta1StorageVersionMigration_Status_Conditions {
  lastTransitionTime?: string | Computed<string>;
  message?: string | Computed<string>;
  observedGeneration?: number | Computed<number>;
  reason?: string | Computed<string>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface V1beta1StorageVersionMigration_Status {
  /** The latest available observations of the migration's current state. */
  conditions?: V1beta1StorageVersionMigration_Status_Conditions[] | Computed<V1beta1StorageVersionMigration_Status_Conditions[]>;
  /** ResourceVersion to compare with the GC cache for performing the migration. This is the current resource version of given group, version and resource when kube-controller-manager first observes this StorageVersionMigration resource. */
  resourceVersion?: string | Computed<string>;
}

const V1beta1StorageVersionMigration_Metadata_ManagedFieldsFields: FieldMap = {
  apiVersion: "api_version",
  fieldsType: "fields_type",
  fieldsV1: "fields_v1",
  manager: "manager",
  operation: "operation",
  subresource: "subresource",
  time: "time",
};

const V1beta1StorageVersionMigration_Metadata_OwnerReferencesFields: FieldMap = {
  apiVersion: "api_version",
  blockOwnerDeletion: "block_owner_deletion",
  controller: "controller",
  kind: "kind",
  name: "name",
  uid: "uid",
};

const V1beta1StorageVersionMigration_MetadataFields: FieldMap = {
  annotations: "annotations",
  creationTimestamp: "creation_timestamp",
  deletionGracePeriodSeconds: "deletion_grace_period_seconds",
  deletionTimestamp: "deletion_timestamp",
  finalizers: "finalizers",
  generateName: "generate_name",
  generation: "generation",
  labels: "labels",
  managedFields: {
    wireName: "managed_fields",
    kind: "list",
    fields: V1beta1StorageVersionMigration_Metadata_ManagedFieldsFields,
  },
  name: "name",
  namespace: "namespace",
  ownerReferences: {
    wireName: "owner_references",
    kind: "list",
    fields: V1beta1StorageVersionMigration_Metadata_OwnerReferencesFields,
  },
  resourceVersion: "resource_version",
  selfLink: "self_link",
  uid: "uid",
};

const V1beta1StorageVersionMigration_Spec_ResourceFields: FieldMap = {
  group: "group",
  resource: "resource",
};

const V1beta1StorageVersionMigration_SpecFields: FieldMap = {
  resource: {
    wireName: "resource",
    kind: "object",
    fields: V1beta1StorageVersionMigration_Spec_ResourceFields,
  },
};

const V1beta1StorageVersionMigration_Status_ConditionsFields: FieldMap = {
  lastTransitionTime: "last_transition_time",
  message: "message",
  observedGeneration: "observed_generation",
  reason: "reason",
  status: "status",
  type: "type",
};

const V1beta1StorageVersionMigration_StatusFields: FieldMap = {
  conditions: {
    wireName: "conditions",
    kind: "list",
    fields: V1beta1StorageVersionMigration_Status_ConditionsFields,
  },
  resourceVersion: "resource_version",
};

export interface V1beta1StorageVersionMigrationConfig {
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion?: string | Computed<string>;
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind?: string | Computed<string>;
  /** ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create. */
  metadata?: V1beta1StorageVersionMigration_Metadata | Computed<V1beta1StorageVersionMigration_Metadata>;
  /** Spec of the storage version migration. */
  spec?: V1beta1StorageVersionMigration_Spec | Computed<V1beta1StorageVersionMigration_Spec>;
  /** Status of the storage version migration. */
  status?: V1beta1StorageVersionMigration_Status | Computed<V1beta1StorageVersionMigration_Status>;
  /** path parameter, not part of the API's own resource representation */
  name: string | Computed<string>;
}

export interface V1beta1StorageVersionMigrationAttrs {
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion: string;
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind: string;
  /** ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create. */
  metadata: V1beta1StorageVersionMigration_Metadata;
  /** Spec of the storage version migration. */
  spec: V1beta1StorageVersionMigration_Spec;
  /** Status of the storage version migration. */
  status: V1beta1StorageVersionMigration_Status;
  /** path parameter, not part of the API's own resource representation */
  name: string;
}

export const V1beta1StorageVersionMigration: ResourceBinding<V1beta1StorageVersionMigrationConfig, V1beta1StorageVersionMigrationAttrs> = {
  wireType: "kubernetes_storagemigration_v1beta1_storage_version_migration",
  fields: {
    apiVersion: "api_version",
    kind: "kind",
    metadata: {
      wireName: "metadata",
      kind: "object",
      fields: V1beta1StorageVersionMigration_MetadataFields,
    },
    spec: {
      wireName: "spec",
      kind: "object",
      fields: V1beta1StorageVersionMigration_SpecFields,
    },
    status: {
      wireName: "status",
      kind: "object",
      fields: V1beta1StorageVersionMigration_StatusFields,
    },
    name: "name",
  },
};
