# Code generated by `ubx sdk gen` from kubernetes_role_binding_v1. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class BindingV1_Metadata:
    annotations: Any = None
    generate_name: Any = None
    generation: Any = None
    labels: Any = None
    name: Any = None
    namespace: Any = None
    resource_version: Any = None
    uid: Any = None

@dataclasses.dataclass
class BindingV1_RoleRef:
    api_group: Any = None
    kind: Any = None
    name: Any = None

@dataclasses.dataclass
class BindingV1_Subject:
    api_group: Any = None
    kind: Any = None
    name: Any = None
    namespace: Any = None

_BindingV1_MetadataFields = {
    "annotations": ubx.FieldSpec(wire_name="annotations"),
    "generate_name": ubx.FieldSpec(wire_name="generate_name"),
    "generation": ubx.FieldSpec(wire_name="generation"),
    "labels": ubx.FieldSpec(wire_name="labels"),
    "name": ubx.FieldSpec(wire_name="name"),
    "namespace": ubx.FieldSpec(wire_name="namespace"),
    "resource_version": ubx.FieldSpec(wire_name="resource_version"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_BindingV1_RoleRefFields = {
    "api_group": ubx.FieldSpec(wire_name="api_group"),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_BindingV1_SubjectFields = {
    "api_group": ubx.FieldSpec(wire_name="api_group"),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "namespace": ubx.FieldSpec(wire_name="namespace"),
}

@dataclasses.dataclass
class BindingV1Config:
    id: Any = None
    metadata: Any = None
    role_ref: Any = None
    subject: Any = None

BindingV1 = ubx.ResourceBinding(
    wire_type="kubernetes_role_binding_v1",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "metadata": ubx.FieldSpec(
            wire_name="metadata",
            kind="list",
            fields=_BindingV1_MetadataFields,
        ),
        "role_ref": ubx.FieldSpec(
            wire_name="role_ref",
            kind="list",
            fields=_BindingV1_RoleRefFields,
        ),
        "subject": ubx.FieldSpec(
            wire_name="subject",
            kind="list",
            fields=_BindingV1_SubjectFields,
        ),
    },
)
