# Code generated by `ubx sdk gen` from kubernetes_resource_resource_pool_status_request. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ResourcePoolStatusRequest_Metadata_ManagedFields:
    # api_version is the version of the resource that this field set applies to, in the format 'group/version', used to track the version for field management. (AI-inferred)
    api_version: Any = None
    # The type of the fields structure in a Kubernetes managedFields entry, typically 'FieldsV1'. (AI-inferred)
    fields_type: Any = None
    # A JSON representation of the fields managed by a particular operation, as part of Kubernetes managedFields metadata. It contains a map of field names to values indicating which fields were changed by that operation. (AI-inferred)
    fields_v1: Any = None
    # The name of the actor that last applied or mutated the field. In Kubernetes, this is typically the component name (e.g., kube-controller-manager) that owns the field update. (AI-inferred)
    manager: Any = None
    # The operation performed on the managed field. Allowed values are 'Apply' and 'Update'. (AI-inferred)
    operation: Any = None
    # The subresource that the managed field entry applies to, such as 'status' or 'scale'. (AI-inferred)
    subresource: Any = None
    # The timestamp (RFC3339 format) at which the operation recorded in this managedFields entry was performed. (AI-inferred)
    time: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Metadata_OwnerReferences:
    # The API version of the referenced owner resource, e.g., 'v1' or 'apps/v1'. (AI-inferred)
    api_version: Any = None
    # If true, and the owner has the 'foregroundDeletion' finalizer, the owner cannot be deleted until this reference is removed. Defaults to false. (AI-inferred)
    block_owner_deletion: Any = None
    # Indicates whether this owner reference is the managing controller for the resource. (AI-inferred)
    controller: Any = None
    # The kind of the owning Kubernetes resource, as defined in the Kubernetes API. (AI-inferred)
    kind: Any = None
    # The name of the Kubernetes object that owns this resource, as referenced in the owner reference. (AI-inferred)
    name: Any = None
    # The UID of the owner object referenced by this owner reference. (AI-inferred)
    uid: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Metadata:
    # Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
    annotations: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    creation_timestamp: Any = None
    # Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
    deletion_grace_period_seconds: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    deletion_timestamp: Any = None
    # Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
    finalizers: Any = None
    # GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
    generate_name: Any = None
    # A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
    generation: Any = None
    # Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
    labels: Any = None
    # ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
    managed_fields: Any = None
    # Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
    name: Any = None
    # Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
    namespace: Any = None
    # List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
    owner_references: Any = None
    # An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
    resource_version: Any = None
    # Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
    self_link: Any = None
    # UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
    uid: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Spec:
    # DefaultPartitionTypeAttribute optionally names a device attribute (by its fully qualified name, e.g. "gpu.example.com/profile") to use as the default grouping attribute for partitionable devices whose slice has not declared one themselves. A slice's own PartitionTypeAttribute always takes precedence. This default applies only to devices whose slice does not declare one, so that a request can still get an accurate partitionSummary from a driver that has not been updated to declare it. When neither the slice nor this default names an attribute, a partitionable pool reports no partitionSummary. Must include the domain qualifier.
    default_partition_type_attribute: Any = None
    # Driver specifies the DRA driver name to filter pools. Only pools from ResourceSlices with this driver will be included. Must be a DNS subdomain (e.g., "gpu.example.com").
    driver: Any = None
    # Limit optionally specifies the maximum number of pools to return in the status. If more pools match the filter criteria, the response will be truncated (i.e., len(status.pools) < status.poolCount). Default: 100 Minimum: 1 Maximum: 1000
    limit: Any = None
    # PoolName optionally filters to a specific pool name. If not specified, all pools from the specified driver are included. When specified, must be a non-empty valid resource pool name (DNS subdomains separated by "/").
    pool_name: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status_Conditions:
    # The last time the condition transitioned from one status to another. Represented as a string in RFC3339 format (e.g., 2023-01-01T00:00:00Z). (AI-inferred)
    last_transition_time: Any = None
    # Human-readable message providing details about the condition, such as why the resource pool is in the current state. (AI-inferred)
    message: Any = None
    # The generation of the resource pool status request that was observed by the controller when this condition was last updated. This is used to determine whether the condition reflects the latest desired state. (AI-inferred)
    observed_generation: Any = None
    # A machine-readable, CamelCase reason for the condition's last transition. (AI-inferred)
    reason: Any = None
    # The status of the condition, typically one of "True", "False", or "Unknown". (AI-inferred)
    status: Any = None
    # The type of the condition, indicating the specific aspect of the resource pool status being reported (e.g., Ready, Error). (AI-inferred)
    type: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status_Pools_PartitionSummary:
    allocatable: Any = None
    attribute: Any = None
    total: Any = None
    type: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status_Pools_ShareableSummary_Capacity:
    # The amount of resource capacity currently available for allocation in the shared resource pool, expressed as a Kubernetes quantity string (e.g., '10Gi'). (AI-inferred)
    available: Any = None
    # The amount of the shareable capacity that has been consumed, expressed as a Kubernetes resource quantity (e.g., '1Gi'). (AI-inferred)
    consumed: Any = None
    name: Any = None
    total: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status_Pools_ShareableSummary:
    capacity: Any = None
    # The number of devices in the resource pool's shareable summary that are fully available, meaning the entire device is not in use and can be allocated. (AI-inferred)
    fully_available_devices: Any = None
    # Number of devices in the pool that are partially available, meaning they have some capacity already used but still have free resources to be shared. (AI-inferred)
    partially_available_devices: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status_Pools:
    # The number of devices currently allocated from the resource pool. (AI-inferred)
    allocated_devices: Any = None
    # The number of devices currently available for use in the resource pool. (AI-inferred)
    available_devices: Any = None
    driver: Any = None
    generation: Any = None
    # The name of the Kubernetes node associated with this resource pool. (AI-inferred)
    node_name: Any = None
    partition_summary: Any = None
    pool_name: Any = None
    # The number of resource slices in the resource pool. (AI-inferred)
    resource_slice_count: Any = None
    shareable_summary: Any = None
    # The total number of devices (e.g., GPUs, NICs) available in the resource pool. (AI-inferred)
    total_devices: Any = None
    # The number of devices in the resource pool that are currently unavailable. (AI-inferred)
    unavailable_devices: Any = None
    validation_error: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequest_Status:
    # Conditions provide information about the state of the request. A condition with type=Complete or type=Failed will always be set when the status is populated. Known condition types: - "Complete": True when the request has been processed successfully - "Failed": True when the request could not be processed
    conditions: Any = None
    # PoolCount is the total number of pools that matched the filter criteria, regardless of truncation. This helps users understand how many pools exist even when the response is truncated. A value of 0 means no pools matched the filter criteria.
    pool_count: Any = None
    # Pools contains the first `spec.limit` matching pools, sorted by driver then pool name. If `len(pools) < poolCount`, the list was truncated. When omitted, no pools matched the request filters.
    pools: Any = None

_ResourcePoolStatusRequest_Metadata_ManagedFieldsFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "fields_type": ubx.FieldSpec(wire_name="fields_type"),
    "fields_v1": ubx.FieldSpec(wire_name="fields_v1"),
    "manager": ubx.FieldSpec(wire_name="manager"),
    "operation": ubx.FieldSpec(wire_name="operation"),
    "subresource": ubx.FieldSpec(wire_name="subresource"),
    "time": ubx.FieldSpec(wire_name="time"),
}

_ResourcePoolStatusRequest_Metadata_OwnerReferencesFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "block_owner_deletion": ubx.FieldSpec(wire_name="block_owner_deletion"),
    "controller": ubx.FieldSpec(wire_name="controller"),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_ResourcePoolStatusRequest_MetadataFields = {
    "annotations": ubx.FieldSpec(wire_name="annotations"),
    "creation_timestamp": ubx.FieldSpec(wire_name="creation_timestamp"),
    "deletion_grace_period_seconds": ubx.FieldSpec(wire_name="deletion_grace_period_seconds"),
    "deletion_timestamp": ubx.FieldSpec(wire_name="deletion_timestamp"),
    "finalizers": ubx.FieldSpec(wire_name="finalizers"),
    "generate_name": ubx.FieldSpec(wire_name="generate_name"),
    "generation": ubx.FieldSpec(wire_name="generation"),
    "labels": ubx.FieldSpec(wire_name="labels"),
    "managed_fields": ubx.FieldSpec(
        wire_name="managed_fields",
        kind="list",
        fields=_ResourcePoolStatusRequest_Metadata_ManagedFieldsFields,
    ),
    "name": ubx.FieldSpec(wire_name="name"),
    "namespace": ubx.FieldSpec(wire_name="namespace"),
    "owner_references": ubx.FieldSpec(
        wire_name="owner_references",
        kind="list",
        fields=_ResourcePoolStatusRequest_Metadata_OwnerReferencesFields,
    ),
    "resource_version": ubx.FieldSpec(wire_name="resource_version"),
    "self_link": ubx.FieldSpec(wire_name="self_link"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_ResourcePoolStatusRequest_SpecFields = {
    "default_partition_type_attribute": ubx.FieldSpec(wire_name="default_partition_type_attribute"),
    "driver": ubx.FieldSpec(wire_name="driver"),
    "limit": ubx.FieldSpec(wire_name="limit"),
    "pool_name": ubx.FieldSpec(wire_name="pool_name"),
}

_ResourcePoolStatusRequest_Status_ConditionsFields = {
    "last_transition_time": ubx.FieldSpec(wire_name="last_transition_time"),
    "message": ubx.FieldSpec(wire_name="message"),
    "observed_generation": ubx.FieldSpec(wire_name="observed_generation"),
    "reason": ubx.FieldSpec(wire_name="reason"),
    "status": ubx.FieldSpec(wire_name="status"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_ResourcePoolStatusRequest_Status_Pools_PartitionSummaryFields = {
    "allocatable": ubx.FieldSpec(wire_name="allocatable"),
    "attribute": ubx.FieldSpec(wire_name="attribute"),
    "total": ubx.FieldSpec(wire_name="total"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_ResourcePoolStatusRequest_Status_Pools_ShareableSummary_CapacityFields = {
    "available": ubx.FieldSpec(wire_name="available"),
    "consumed": ubx.FieldSpec(wire_name="consumed"),
    "name": ubx.FieldSpec(wire_name="name"),
    "total": ubx.FieldSpec(wire_name="total"),
}

_ResourcePoolStatusRequest_Status_Pools_ShareableSummaryFields = {
    "capacity": ubx.FieldSpec(
        wire_name="capacity",
        kind="list",
        fields=_ResourcePoolStatusRequest_Status_Pools_ShareableSummary_CapacityFields,
    ),
    "fully_available_devices": ubx.FieldSpec(wire_name="fully_available_devices"),
    "partially_available_devices": ubx.FieldSpec(wire_name="partially_available_devices"),
}

_ResourcePoolStatusRequest_Status_PoolsFields = {
    "allocated_devices": ubx.FieldSpec(wire_name="allocated_devices"),
    "available_devices": ubx.FieldSpec(wire_name="available_devices"),
    "driver": ubx.FieldSpec(wire_name="driver"),
    "generation": ubx.FieldSpec(wire_name="generation"),
    "node_name": ubx.FieldSpec(wire_name="node_name"),
    "partition_summary": ubx.FieldSpec(
        wire_name="partition_summary",
        kind="list",
        fields=_ResourcePoolStatusRequest_Status_Pools_PartitionSummaryFields,
    ),
    "pool_name": ubx.FieldSpec(wire_name="pool_name"),
    "resource_slice_count": ubx.FieldSpec(wire_name="resource_slice_count"),
    "shareable_summary": ubx.FieldSpec(
        wire_name="shareable_summary",
        kind="object",
        fields=_ResourcePoolStatusRequest_Status_Pools_ShareableSummaryFields,
    ),
    "total_devices": ubx.FieldSpec(wire_name="total_devices"),
    "unavailable_devices": ubx.FieldSpec(wire_name="unavailable_devices"),
    "validation_error": ubx.FieldSpec(wire_name="validation_error"),
}

_ResourcePoolStatusRequest_StatusFields = {
    "conditions": ubx.FieldSpec(
        wire_name="conditions",
        kind="list",
        fields=_ResourcePoolStatusRequest_Status_ConditionsFields,
    ),
    "pool_count": ubx.FieldSpec(wire_name="pool_count"),
    "pools": ubx.FieldSpec(
        wire_name="pools",
        kind="list",
        fields=_ResourcePoolStatusRequest_Status_PoolsFields,
    ),
}

@dataclasses.dataclass
class ResourcePoolStatusRequestConfig:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ResourcePoolStatusRequestSpec defines the filters for the pool status request.
    spec: Any = None
    # ResourcePoolStatusRequestStatus contains the calculated pool status information.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

@dataclasses.dataclass
class ResourcePoolStatusRequestAttrs:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ResourcePoolStatusRequestSpec defines the filters for the pool status request.
    spec: Any = None
    # ResourcePoolStatusRequestStatus contains the calculated pool status information.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

ResourcePoolStatusRequest = ubx.ResourceBinding(
    wire_type="kubernetes_resource_resource_pool_status_request",
    fields={
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "kind": ubx.FieldSpec(wire_name="kind"),
        "metadata": ubx.FieldSpec(
            wire_name="metadata",
            kind="object",
            fields=_ResourcePoolStatusRequest_MetadataFields,
        ),
        "spec": ubx.FieldSpec(
            wire_name="spec",
            kind="object",
            fields=_ResourcePoolStatusRequest_SpecFields,
        ),
        "status": ubx.FieldSpec(
            wire_name="status",
            kind="object",
            fields=_ResourcePoolStatusRequest_StatusFields,
        ),
        "name": ubx.FieldSpec(wire_name="name"),
    },
)
