# Code generated by `ubx sdk gen` from kubernetes_resource_v1beta1_resource_claim. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class V1beta1ResourceClaim_Metadata_ManagedFields:
    # The API version used to manage the fields in this managedFields entry. (AI-inferred)
    api_version: Any = None
    # The type of the fields field. Currently only 'FieldsV1' is supported. (AI-inferred)
    fields_type: Any = None
    # fields_v1 is the Kubernetes fieldsV1 field, which contains a JSON representation of the fields managed by this entry. It stores a set of field paths and their ownership information used for server-side apply conflict detection. (AI-inferred)
    fields_v1: Any = None
    # The name of the manager (entity, such as a controller or user) that last applied or updated the managed fields. (AI-inferred)
    manager: Any = None
    # Operation is the type of operation that last modified the field, such as 'Update' or 'Apply'. (AI-inferred)
    operation: Any = None
    # The subresource of the resource that this managed field entry applies to, such as 'status' or 'scale'. (AI-inferred)
    subresource: Any = None
    # Time is the timestamp, in RFC3339 format, when the managed fields entry was last updated. (AI-inferred)
    time: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Metadata_OwnerReferences:
    # The API version of the referenced owner object, e.g. 'v1' or 'apps/v1'. This matches the apiVersion field of the owner's resource. (AI-inferred)
    api_version: Any = None
    # If true, prevents deletion of the owner object if this dependent resource would prevent the owner's garbage collection. This is part of the standard Kubernetes OwnerReference schema and helps ensure safe deletion ordering. (AI-inferred)
    block_owner_deletion: Any = None
    # Indicates whether the owner reference is the managing controller for the resource. This matches the `controller` field in Kubernetes OwnerReference, which is a boolean pointer (set to true when the owner is the primary controller). (AI-inferred)
    controller: Any = None
    # The kind of the referenced owner resource, matching the API resource type for the owner (e.g., 'Deployment'). (AI-inferred)
    kind: Any = None
    # The name of the owner object that this owner_reference points to. In Kubernetes, this matches the name of the referenced resource as defined in its metadata. (AI-inferred)
    name: Any = None
    # UID of the referenced owner object. (AI-inferred)
    uid: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Metadata:
    # Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
    annotations: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    creation_timestamp: Any = None
    # Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
    deletion_grace_period_seconds: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    deletion_timestamp: Any = None
    # Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
    finalizers: Any = None
    # GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
    generate_name: Any = None
    # A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
    generation: Any = None
    # Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
    labels: Any = None
    # ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
    managed_fields: Any = None
    # Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
    name: Any = None
    # Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
    namespace: Any = None
    # List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
    owner_references: Any = None
    # An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
    resource_version: Any = None
    # Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
    self_link: Any = None
    # UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
    uid: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Config_Opaque:
    # Specifies the name of the driver that interprets the opaque device configuration parameters. (AI-inferred)
    driver: Any = None
    # Arbitrary JSON object containing driver-specific parameters. The cluster does not interpret these parameters; they are passed as-is to the device driver. (AI-inferred)
    parameters: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Config:
    # Opaque carries driver-specific configuration parameters in a raw object, allowing the device driver to interpret the settings without Kubernetes understanding them. (AI-inferred)
    opaque: Any = None
    # Which of this claim's own device requests this configuration applies to -- every request, when left empty. (AI-inferred)
    requests: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Constraints:
    # The name of a device attribute that all devices selected for the request must have different values for, ensuring the devices are distinct with respect to that attribute. (AI-inferred)
    distinct_attribute: Any = None
    # The name of the device attribute this constraint applies to. A device is selected only if it has this attribute with a value matching the constraint's 'value' field. (AI-inferred)
    match_attribute: Any = None
    # A list of request names that this constraint applies to. If empty, the constraint applies to all requests in the claim. (AI-inferred)
    requests: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_Capacity:
    # The real, minimum quantity requested for each named device capacity. (AI-inferred)
    requests: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_DerivedAttributes:
    # The real CEL expression computing this derived attribute's own value from the allocated device. (AI-inferred)
    expression: Any = None
    # The real name this derived attribute is exposed under on the resulting allocation. (AI-inferred)
    name: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_Selectors_Cel:
    # The CEL expression used to select devices that satisfy this request. It is evaluated against each device's attributes and must return true for the device to be matched. (AI-inferred)
    expression: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_Selectors:
    # CEL (Common Expression Language) selector for device allocation. The expression is evaluated against device attributes to determine which devices match the request; a device is selected if the expression evaluates to true. This is an alternative to the serial selector. (AI-inferred)
    cel: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_Tolerations:
    # The effect of the taint to match. Valid values are 'NoSchedule', 'PreferNoSchedule', and 'NoExecute'. An empty value matches all taint effects. (AI-inferred)
    effect: Any = None
    # The key of the taint that this toleration matches. When the operator is 'Exists', the value must be empty. (AI-inferred)
    key: Any = None
    # The operator used to match the taint key. Valid values are 'Exists' and 'Equal'. Defaults to 'Equal'. When 'Exists' is set, the value must be empty and the toleration matches all taints with the specified key. (AI-inferred)
    operator: Any = None
    # The duration in seconds for which the toleration tolerates the taint when the effect is NoExecute. If omitted, the toleration lasts forever. (AI-inferred)
    toleration_seconds: Any = None
    # The value associated with the key of the toleration. This is used with the operator to determine a match, e.g., when operator is Equal, the value must match the taint's value; when operator is Exists, this field is ignored. (AI-inferred)
    value: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable:
    # The allocation mode for the device request. In the Kubernetes DRA API, this can be 'All' (allocate all matching devices) or 'Exact' (allocate the specified number of matching devices). (AI-inferred)
    allocation_mode: Any = None
    # Real, minimum capacity requirements (per named capacity) this prioritized sub-request's own matched device must satisfy. (AI-inferred)
    capacity: Any = None
    # Number of devices to allocate from the first available devices that match the request's class and selectors. (AI-inferred)
    count: Any = None
    # Real, computed attributes (a CEL expression evaluated per allocated device) exposed on the resulting allocation, not present on the device itself. (AI-inferred)
    derived_attributes: Any = None
    # The name of the DeviceClass that the requested device must belong to when using the firstAvailable selector. Only devices from the named class are eligible for allocation. (AI-inferred)
    device_class_name: Any = None
    # The real name identifying this alternative sub-request within its own parent request's `first_available` list -- what an allocation result reports as actually satisfied. (AI-inferred)
    name: Any = None
    # A list of device selectors used to filter devices from the requested device class. Each selector is a CEL expression evaluated against device attributes; multiple selectors are combined with AND logic. If empty, all devices of the class are considered for allocation. (AI-inferred)
    selectors: Any = None
    # List of tolerations that apply to this device request in a Kubernetes ResourceClaim. Tolerations allow scheduling onto nodes with matching taints, similar to pod tolerations. (AI-inferred)
    tolerations: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices_Requests:
    # Whether this device request grants the claim admin-level access to the device, bypassing the device's own normal usage restrictions -- only usable in a namespace explicitly labeled to allow it. (AI-inferred)
    admin_access: Any = None
    # How many devices this request needs -- `ExactCount` for a specific `count`, or `All` for every device matching its selectors. (AI-inferred)
    allocation_mode: Any = None
    # Real, minimum capacity requirements (per named capacity) this request's own matched device(s) must satisfy. (AI-inferred)
    capacity: Any = None
    # How many devices to allocate, when `allocation_mode` is `ExactCount`. (AI-inferred)
    count: Any = None
    # Real, computed attributes (a CEL expression evaluated per allocated device) exposed on the resulting allocation, not present on the device itself. (AI-inferred)
    derived_attributes: Any = None
    # The real DeviceClass this request selects candidate devices from. (AI-inferred)
    device_class_name: Any = None
    # An ordered list of DeviceRequest alternatives; the first one that can be satisfied will be allocated. (AI-inferred)
    first_available: Any = None
    # Name of the device request. Must be unique within the requests list. (AI-inferred)
    name: Any = None
    # Real CEL device selectors every candidate device must satisfy to match this request. (AI-inferred)
    selectors: Any = None
    # Real tolerations letting this request's own matched devices carry a taint the request is willing to accept. (AI-inferred)
    tolerations: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec_Devices:
    # This field holds configuration for multiple potential drivers which could satisfy requests in this claim. It is ignored while allocating the claim.
    config: Any = None
    # These constraints must be satisfied by the set of devices that get allocated for the claim.
    constraints: Any = None
    # Requests represent individual requests for distinct devices which must all be satisfied. If empty, nothing needs to be allocated.
    requests: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Spec:
    # DeviceClaim defines how to request devices with a ResourceClaim.
    devices: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_Devices_Config:
    # Opaque provides driver-specific configuration parameters for the device allocation. It is used when the configuration source is 'FromData'. (AI-inferred)
    opaque: Any = None
    # Which of this claim's own device requests this configuration applies to -- every request, when left empty. (AI-inferred)
    requests: Any = None
    # Source indicates the origin of the device allocation configuration. Valid values are 'claim' (configuration from the ResourceClaim) and 'driver' (configuration from the driver). (AI-inferred)
    source: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_Devices_Results:
    # Indicates whether the device was allocated with administrative access. (AI-inferred)
    admin_access: Any = None
    # Real cluster conditions (matching a device's own `binding_conditions`) that must hold before this allocated device is actually usable by the pod. (AI-inferred)
    binding_conditions: Any = None
    # A list of conditions that describe why the binding of the resource to the claim failed. In the Kubernetes ResourceClaim status, this field is populated with error reasons when the scheduler cannot allocate the requested devices. (AI-inferred)
    binding_failure_conditions: Any = None
    # The real, actual capacity quantities this allocation consumed from the device's own advertised capacity. (AI-inferred)
    consumed_capacity: Any = None
    # The name of the device that was allocated from the pool for this resource claim, as reported by the resource driver. (AI-inferred)
    device: Any = None
    # The name of the device driver that provides the allocated device. (AI-inferred)
    driver: Any = None
    # The name of the resource pool from which the device was allocated. (AI-inferred)
    pool: Any = None
    # The name of the device request that this allocation result corresponds to. (AI-inferred)
    request: Any = None
    # ShareID is a string that uniquely identifies a shared device across multiple resource claims. If the device is not shared, this field is omitted. (AI-inferred)
    share_id: Any = None
    # A list of node operations that the driver has indicated should be skipped for this allocated device. These operations are normally performed by the kubelet during device preparation, but are skipped for devices that do not require them. (AI-inferred)
    skip_node_operations: Any = None
    # The real tolerations this allocation result was granted under, letting it keep using a device that later gained a matching taint. (AI-inferred)
    tolerations: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_Devices:
    # This field is a combination of all the claim and class configuration parameters. Drivers can distinguish between those based on a flag. This includes configuration parameters for drivers which have no allocated devices in the result because it is up to the drivers which configuration parameters they support. They can silently ignore unknown configuration parameters.
    config: Any = None
    # Results lists all allocated devices.
    results: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTerms_MatchExpressions:
    # The label key that the selector expression applies to. It must be a valid Kubernetes label key (e.g., 'disktype' or 'kubernetes.io/os'). (AI-inferred)
    key: Any = None
    # The operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist, Gt, and Lt. (AI-inferred)
    operator: Any = None
    # values is the list of strings that correspond to the key. For example, if operator is In or NotIn, the key's value must be in (or not in) this list. (AI-inferred)
    values: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTerms:
    # A list of node selector requirements by node's labels. (AI-inferred)
    match_expressions: Any = None
    # match_fields is a list of node selector requirements that specify the node fields (e.g., metadata.name) that must match for a node to be selected by this node selector term. (AI-inferred)
    match_fields: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation_NodeSelector:
    # Required. A list of node selector terms. The terms are ORed.
    node_selector_terms: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Allocation:
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    allocation_timestamp: Any = None
    # DeviceAllocationResult is the result of allocating devices.
    devices: Any = None
    # A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
    node_selector: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Devices_Conditions:
    # lastTransitionTime is the last time the condition transitioned from one status to another. This timestamp is typically represented in RFC3339 format. (AI-inferred)
    last_transition_time: Any = None
    # A human-readable message providing details about the current condition of the device in the resource claim. (AI-inferred)
    message: Any = None
    # observedGeneration is the .metadata.generation of the ResourceClaim that this condition was observed against, indicating the freshness of the condition relative to the latest generation. (AI-inferred)
    observed_generation: Any = None
    # Reason is a machine-readable, CamelCase reason for the condition's last transition, providing a stable identifier for the cause of the condition. (AI-inferred)
    reason: Any = None
    # The status of the condition, typically 'True', 'False', or 'Unknown'. (AI-inferred)
    status: Any = None
    # The real, named condition type (e.g. whether the device is still healthy and reachable) this status condition reports on. (AI-inferred)
    type: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Devices_NetworkData:
    # The MAC address of the network interface allocated for this resource claim. (AI-inferred)
    hardware_address: Any = None
    # The name of the network interface on the node where this device is allocated. (AI-inferred)
    interface_name: Any = None
    # List of IP addresses assigned to the network device. (AI-inferred)
    ips: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_Devices:
    # The list of conditions representing the latest observed state of the device. Each condition includes the type, status, reason, and message to indicate the device's health status. (AI-inferred)
    conditions: Any = None
    # Arbitrary driver-specific data about the device allocation, as provided by the resource driver. Kubernetes does not interpret this field and it may be used to pass device-specific configuration or status. (AI-inferred)
    data: Any = None
    # The name of the device that has been allocated for this resource claim. (AI-inferred)
    device: Any = None
    # The name of the device driver that manages this allocated device, matching the driver specified in the corresponding DeviceClass. (AI-inferred)
    driver: Any = None
    # Network information for the allocated device, including its interface name, IP addresses, and MAC address. (AI-inferred)
    network_data: Any = None
    # The name of the resource pool (ResourceSlice) from which this device was allocated. (AI-inferred)
    pool: Any = None
    # A real, unique identifier for this specific share of a device that supports being allocated to more than one claim at once. (AI-inferred)
    share_id: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status_ReservedFor:
    # The API group of the resource that reserved this claim. For core resources, this is the empty string; otherwise it is the fully-qualified API group name. (AI-inferred)
    api_group: Any = None
    # The name of the pod that this resource claim is reserved for. (AI-inferred)
    name: Any = None
    # The name of the resource (e.g., a Pod) that holds a reservation for this resource claim, as recorded in the status.reservedFor list. (AI-inferred)
    resource: Any = None
    # The UID of the consumer (e.g., a Pod) that this ResourceClaim is reserved for. This is part of the ResourceClaimConsumerReference in the reservedFor list. (AI-inferred)
    uid: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaim_Status:
    # AllocationResult contains attributes of an allocated resource.
    allocation: Any = None
    # Devices contains the status of each device allocated for this claim, as reported by the driver. This can include driver-specific information. Entries are owned by their respective drivers.
    devices: Any = None
    # ReservedFor indicates which entities are currently allowed to use the claim. A Pod which references a ResourceClaim which is not reserved for that Pod will not be started. A claim that is in use or might be in use because it has been reserved must not get deallocated. In a cluster with multiple scheduler instances, two pods might get scheduled concurrently by different schedulers. When they reference the same ResourceClaim which already has reached its maximum number of consumers, only one pod can be scheduled. Both schedulers try to add their pod to the claim.status.reservedFor field, but only the update that reaches the API server first gets stored. The other one fails with an error and the scheduler which issued it knows that it must put the pod back into the queue, waiting for the ResourceClaim to become usable again. There can be at most 256 such reservations. This may get increased in the future, but not reduced.
    reserved_for: Any = None

_V1beta1ResourceClaim_Metadata_ManagedFieldsFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "fields_type": ubx.FieldSpec(wire_name="fields_type"),
    "fields_v1": ubx.FieldSpec(wire_name="fields_v1"),
    "manager": ubx.FieldSpec(wire_name="manager"),
    "operation": ubx.FieldSpec(wire_name="operation"),
    "subresource": ubx.FieldSpec(wire_name="subresource"),
    "time": ubx.FieldSpec(wire_name="time"),
}

_V1beta1ResourceClaim_Metadata_OwnerReferencesFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "block_owner_deletion": ubx.FieldSpec(wire_name="block_owner_deletion"),
    "controller": ubx.FieldSpec(wire_name="controller"),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_V1beta1ResourceClaim_MetadataFields = {
    "annotations": ubx.FieldSpec(wire_name="annotations"),
    "creation_timestamp": ubx.FieldSpec(wire_name="creation_timestamp"),
    "deletion_grace_period_seconds": ubx.FieldSpec(wire_name="deletion_grace_period_seconds"),
    "deletion_timestamp": ubx.FieldSpec(wire_name="deletion_timestamp"),
    "finalizers": ubx.FieldSpec(wire_name="finalizers"),
    "generate_name": ubx.FieldSpec(wire_name="generate_name"),
    "generation": ubx.FieldSpec(wire_name="generation"),
    "labels": ubx.FieldSpec(wire_name="labels"),
    "managed_fields": ubx.FieldSpec(
        wire_name="managed_fields",
        kind="list",
        fields=_V1beta1ResourceClaim_Metadata_ManagedFieldsFields,
    ),
    "name": ubx.FieldSpec(wire_name="name"),
    "namespace": ubx.FieldSpec(wire_name="namespace"),
    "owner_references": ubx.FieldSpec(
        wire_name="owner_references",
        kind="list",
        fields=_V1beta1ResourceClaim_Metadata_OwnerReferencesFields,
    ),
    "resource_version": ubx.FieldSpec(wire_name="resource_version"),
    "self_link": ubx.FieldSpec(wire_name="self_link"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_V1beta1ResourceClaim_Spec_Devices_Config_OpaqueFields = {
    "driver": ubx.FieldSpec(wire_name="driver"),
    "parameters": ubx.FieldSpec(wire_name="parameters"),
}

_V1beta1ResourceClaim_Spec_Devices_ConfigFields = {
    "opaque": ubx.FieldSpec(
        wire_name="opaque",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_Devices_Config_OpaqueFields,
    ),
    "requests": ubx.FieldSpec(wire_name="requests"),
}

_V1beta1ResourceClaim_Spec_Devices_ConstraintsFields = {
    "distinct_attribute": ubx.FieldSpec(wire_name="distinct_attribute"),
    "match_attribute": ubx.FieldSpec(wire_name="match_attribute"),
    "requests": ubx.FieldSpec(wire_name="requests"),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_CapacityFields = {
    "requests": ubx.FieldSpec(wire_name="requests"),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_DerivedAttributesFields = {
    "expression": ubx.FieldSpec(wire_name="expression"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_Selectors_CelFields = {
    "expression": ubx.FieldSpec(wire_name="expression"),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_SelectorsFields = {
    "cel": ubx.FieldSpec(
        wire_name="cel",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_Selectors_CelFields,
    ),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_TolerationsFields = {
    "effect": ubx.FieldSpec(wire_name="effect"),
    "key": ubx.FieldSpec(wire_name="key"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "toleration_seconds": ubx.FieldSpec(wire_name="toleration_seconds"),
    "value": ubx.FieldSpec(wire_name="value"),
}

_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailableFields = {
    "allocation_mode": ubx.FieldSpec(wire_name="allocation_mode"),
    "capacity": ubx.FieldSpec(
        wire_name="capacity",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_CapacityFields,
    ),
    "count": ubx.FieldSpec(wire_name="count"),
    "derived_attributes": ubx.FieldSpec(
        wire_name="derived_attributes",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_DerivedAttributesFields,
    ),
    "device_class_name": ubx.FieldSpec(wire_name="device_class_name"),
    "name": ubx.FieldSpec(wire_name="name"),
    "selectors": ubx.FieldSpec(
        wire_name="selectors",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_SelectorsFields,
    ),
    "tolerations": ubx.FieldSpec(
        wire_name="tolerations",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_TolerationsFields,
    ),
}

_V1beta1ResourceClaim_Spec_Devices_RequestsFields = {
    "admin_access": ubx.FieldSpec(wire_name="admin_access"),
    "allocation_mode": ubx.FieldSpec(wire_name="allocation_mode"),
    "capacity": ubx.FieldSpec(
        wire_name="capacity",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_CapacityFields,
    ),
    "count": ubx.FieldSpec(wire_name="count"),
    "derived_attributes": ubx.FieldSpec(
        wire_name="derived_attributes",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_DerivedAttributesFields,
    ),
    "device_class_name": ubx.FieldSpec(wire_name="device_class_name"),
    "first_available": ubx.FieldSpec(
        wire_name="first_available",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailableFields,
    ),
    "name": ubx.FieldSpec(wire_name="name"),
    "selectors": ubx.FieldSpec(
        wire_name="selectors",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_SelectorsFields,
    ),
    "tolerations": ubx.FieldSpec(
        wire_name="tolerations",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_TolerationsFields,
    ),
}

_V1beta1ResourceClaim_Spec_DevicesFields = {
    "config": ubx.FieldSpec(
        wire_name="config",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_ConfigFields,
    ),
    "constraints": ubx.FieldSpec(
        wire_name="constraints",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_ConstraintsFields,
    ),
    "requests": ubx.FieldSpec(
        wire_name="requests",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_RequestsFields,
    ),
}

_V1beta1ResourceClaim_SpecFields = {
    "devices": ubx.FieldSpec(
        wire_name="devices",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_DevicesFields,
    ),
}

_V1beta1ResourceClaim_Status_Allocation_Devices_ConfigFields = {
    "opaque": ubx.FieldSpec(
        wire_name="opaque",
        kind="object",
        fields=_V1beta1ResourceClaim_Spec_Devices_Config_OpaqueFields,
    ),
    "requests": ubx.FieldSpec(wire_name="requests"),
    "source": ubx.FieldSpec(wire_name="source"),
}

_V1beta1ResourceClaim_Status_Allocation_Devices_ResultsFields = {
    "admin_access": ubx.FieldSpec(wire_name="admin_access"),
    "binding_conditions": ubx.FieldSpec(wire_name="binding_conditions"),
    "binding_failure_conditions": ubx.FieldSpec(wire_name="binding_failure_conditions"),
    "consumed_capacity": ubx.FieldSpec(wire_name="consumed_capacity"),
    "device": ubx.FieldSpec(wire_name="device"),
    "driver": ubx.FieldSpec(wire_name="driver"),
    "pool": ubx.FieldSpec(wire_name="pool"),
    "request": ubx.FieldSpec(wire_name="request"),
    "share_id": ubx.FieldSpec(wire_name="share_id"),
    "skip_node_operations": ubx.FieldSpec(wire_name="skip_node_operations"),
    "tolerations": ubx.FieldSpec(
        wire_name="tolerations",
        kind="list",
        fields=_V1beta1ResourceClaim_Spec_Devices_Requests_FirstAvailable_TolerationsFields,
    ),
}

_V1beta1ResourceClaim_Status_Allocation_DevicesFields = {
    "config": ubx.FieldSpec(
        wire_name="config",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Allocation_Devices_ConfigFields,
    ),
    "results": ubx.FieldSpec(
        wire_name="results",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Allocation_Devices_ResultsFields,
    ),
}

_V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTerms_MatchExpressionsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "values": ubx.FieldSpec(wire_name="values"),
}

_V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTermsFields = {
    "match_expressions": ubx.FieldSpec(
        wire_name="match_expressions",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTerms_MatchExpressionsFields,
    ),
    "match_fields": ubx.FieldSpec(
        wire_name="match_fields",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTerms_MatchExpressionsFields,
    ),
}

_V1beta1ResourceClaim_Status_Allocation_NodeSelectorFields = {
    "node_selector_terms": ubx.FieldSpec(
        wire_name="node_selector_terms",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Allocation_NodeSelector_NodeSelectorTermsFields,
    ),
}

_V1beta1ResourceClaim_Status_AllocationFields = {
    "allocation_timestamp": ubx.FieldSpec(wire_name="allocation_timestamp"),
    "devices": ubx.FieldSpec(
        wire_name="devices",
        kind="object",
        fields=_V1beta1ResourceClaim_Status_Allocation_DevicesFields,
    ),
    "node_selector": ubx.FieldSpec(
        wire_name="node_selector",
        kind="object",
        fields=_V1beta1ResourceClaim_Status_Allocation_NodeSelectorFields,
    ),
}

_V1beta1ResourceClaim_Status_Devices_ConditionsFields = {
    "last_transition_time": ubx.FieldSpec(wire_name="last_transition_time"),
    "message": ubx.FieldSpec(wire_name="message"),
    "observed_generation": ubx.FieldSpec(wire_name="observed_generation"),
    "reason": ubx.FieldSpec(wire_name="reason"),
    "status": ubx.FieldSpec(wire_name="status"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_V1beta1ResourceClaim_Status_Devices_NetworkDataFields = {
    "hardware_address": ubx.FieldSpec(wire_name="hardware_address"),
    "interface_name": ubx.FieldSpec(wire_name="interface_name"),
    "ips": ubx.FieldSpec(wire_name="ips"),
}

_V1beta1ResourceClaim_Status_DevicesFields = {
    "conditions": ubx.FieldSpec(
        wire_name="conditions",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_Devices_ConditionsFields,
    ),
    "data": ubx.FieldSpec(wire_name="data"),
    "device": ubx.FieldSpec(wire_name="device"),
    "driver": ubx.FieldSpec(wire_name="driver"),
    "network_data": ubx.FieldSpec(
        wire_name="network_data",
        kind="object",
        fields=_V1beta1ResourceClaim_Status_Devices_NetworkDataFields,
    ),
    "pool": ubx.FieldSpec(wire_name="pool"),
    "share_id": ubx.FieldSpec(wire_name="share_id"),
}

_V1beta1ResourceClaim_Status_ReservedForFields = {
    "api_group": ubx.FieldSpec(wire_name="api_group"),
    "name": ubx.FieldSpec(wire_name="name"),
    "resource": ubx.FieldSpec(wire_name="resource"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_V1beta1ResourceClaim_StatusFields = {
    "allocation": ubx.FieldSpec(
        wire_name="allocation",
        kind="object",
        fields=_V1beta1ResourceClaim_Status_AllocationFields,
    ),
    "devices": ubx.FieldSpec(
        wire_name="devices",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_DevicesFields,
    ),
    "reserved_for": ubx.FieldSpec(
        wire_name="reserved_for",
        kind="list",
        fields=_V1beta1ResourceClaim_Status_ReservedForFields,
    ),
}

@dataclasses.dataclass
class V1beta1ResourceClaimConfig:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ResourceClaimSpec defines what is being requested in a ResourceClaim and how to configure it.
    spec: Any = None
    # ResourceClaimStatus tracks whether the resource has been allocated and what the result of that was.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    namespace: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

@dataclasses.dataclass
class V1beta1ResourceClaimAttrs:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ResourceClaimSpec defines what is being requested in a ResourceClaim and how to configure it.
    spec: Any = None
    # ResourceClaimStatus tracks whether the resource has been allocated and what the result of that was.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    namespace: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

V1beta1ResourceClaim = ubx.ResourceBinding(
    wire_type="kubernetes_resource_v1beta1_resource_claim",
    fields={
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "kind": ubx.FieldSpec(wire_name="kind"),
        "metadata": ubx.FieldSpec(
            wire_name="metadata",
            kind="object",
            fields=_V1beta1ResourceClaim_MetadataFields,
        ),
        "spec": ubx.FieldSpec(
            wire_name="spec",
            kind="object",
            fields=_V1beta1ResourceClaim_SpecFields,
        ),
        "status": ubx.FieldSpec(
            wire_name="status",
            kind="object",
            fields=_V1beta1ResourceClaim_StatusFields,
        ),
        "namespace": ubx.FieldSpec(wire_name="namespace"),
        "name": ubx.FieldSpec(wire_name="name"),
    },
)
