# Code generated by `ubx sdk gen` from kubernetes_admissionregistration_validating_admission_policy. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Metadata_ManagedFields:
    # The API version of the resource that the field manager used when managing these fields, such as 'admissionregistration.k8s.io/v1'. (AI-inferred)
    api_version: Any = None
    # The type of the managed fields, which indicates the format of the fieldsV1 object. In Kubernetes, this is always 'FieldsV1'. (AI-inferred)
    fields_type: Any = None
    # fields_v1 is a dynamic object that stores the fields owned by the manager, using the Kubernetes FieldsV1 format (a JSON representation with keys like 'f:<fieldName>' that describes the managed fields). (AI-inferred)
    fields_v1: Any = None
    # The name of the manager (e.g., a controller or client) that owns or last modified the tracked fields in this managedFields entry. (AI-inferred)
    manager: Any = None
    # The operation that last modified the managed field, such as Update, Apply, or Delete. (AI-inferred)
    operation: Any = None
    # The subresource to which these managed fields apply. An empty string indicates the main resource, while non-empty values such as 'status' or 'scale' refer to the respective subresource. (AI-inferred)
    subresource: Any = None
    # The timestamp of when the managed field entry was last updated, in RFC3339 format. (AI-inferred)
    time: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Metadata_OwnerReferences:
    # The API version of the referent object as defined in the OwnerReference. (AI-inferred)
    api_version: Any = None
    # If true, and if the owner has the 'foregroundDeletion' finalizer, the owner cannot be deleted from the key-value store until this dependency is deleted. (AI-inferred)
    block_owner_deletion: Any = None
    # If true, this reference points to the managing controller of the object. (AI-inferred)
    controller: Any = None
    # The kind of the owner object in Kubernetes, such as 'Deployment' or 'ConfigMap'. (AI-inferred)
    kind: Any = None
    # The name of the referenced Kubernetes resource (e.g., the object's name within its namespace). (AI-inferred)
    name: Any = None
    # UID of the object referenced by this owner reference. (AI-inferred)
    uid: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Metadata:
    # Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
    annotations: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    creation_timestamp: Any = None
    # Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
    deletion_grace_period_seconds: Any = None
    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
    deletion_timestamp: Any = None
    # Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
    finalizers: Any = None
    # GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
    generate_name: Any = None
    # A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
    generation: Any = None
    # Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
    labels: Any = None
    # ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
    managed_fields: Any = None
    # Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
    name: Any = None
    # Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
    namespace: Any = None
    # List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
    owner_references: Any = None
    # An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
    resource_version: Any = None
    # Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
    self_link: Any = None
    # UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
    uid: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_AuditAnnotations:
    # The key for the audit annotation, which will appear in the audit event for the validating admission policy. (AI-inferred)
    key: Any = None
    # value_expression is a CEL expression that computes the value for the audit annotation. The expression must return a string or a value convertible to a string, and it can access variables from the policy's context. (AI-inferred)
    value_expression: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_MatchConditions:
    # The CEL (Common Expression Language) expression that is evaluated against the request. If the expression evaluates to true, the policy applies to the request. (AI-inferred)
    expression: Any = None
    # The name of the match condition, used to uniquely identify it within the policy. Must be a valid DNS subdomain name. (AI-inferred)
    name: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_MatchConstraints_ExcludeResourceRules:
    # A list of API group names to which this exclude rule applies. An empty list is treated as all API groups; '*' also matches all groups. (AI-inferred)
    api_groups: Any = None
    # The API versions (e.g., 'v1', 'apps/v1') of resources that match this exclusion rule. The rule excludes resources with these API versions. (AI-inferred)
    api_versions: Any = None
    # The list of operations (e.g., CREATE, UPDATE, DELETE, CONNECT) that this exclude rule applies to. To match all operations, use '*'. These operations are excluded from validation for the specified resources. (AI-inferred)
    operations: Any = None
    # An optional list of specific resource names (e.g., pod or service names) to which this exclude rule applies. If empty or omitted, the rule applies to all resources matching the specified api groups, versions, and kinds. (AI-inferred)
    resource_names: Any = None
    # The Kubernetes resource types (e.g., 'pods', 'services') to which this exclusion applies. Requests for these resources are not subject to the policy. (AI-inferred)
    resources: Any = None
    # Scope specifies the scope of the resource rule. Allowed values are '*', 'Cluster', or 'Namespaced'. (AI-inferred)
    scope: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelector_MatchExpressions:
    # The label key that this match expression applies to. Must be a valid Kubernetes label key. (AI-inferred)
    key: Any = None
    # Specifies the relationship between the label key and value(s) in a match expression. Must be one of: In, NotIn, Exists, DoesNotExist. (AI-inferred)
    operator: Any = None
    # The list of values for the label selector expression. Must be provided for operators In and NotIn, and must be empty for Exists and DoesNotExist. (AI-inferred)
    values: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelector:
    # matchExpressions is a list of label selector requirements. The requirements are ANDed.
    match_expressions: Any = None
    # matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
    match_labels: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_MatchConstraints:
    # excludeResourceRules describes what operations on what resources/subresources the ValidatingAdmissionPolicy should not care about. The exclude rules take precedence over include rules (if a resource matches both, it is excluded)
    exclude_resource_rules: Any = None
    # matchPolicy defines how the "MatchResources" list is used to match incoming requests. Allowed values are "Exact" or "Equivalent". - Exact: match a request only if it exactly matches a specified rule. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, but "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`, a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the ValidatingAdmissionPolicy. - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, and "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`, a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the ValidatingAdmissionPolicy. Defaults to "Equivalent"
    match_policy: Any = None
    # A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
    namespace_selector: Any = None
    # A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
    object_selector: Any = None
    # resourceRules describes what operations on what resources/subresources the ValidatingAdmissionPolicy matches. The policy cares about an operation if it matches _any_ Rule.
    resource_rules: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_ParamKind:
    # apiVersion is the API group version the resources belong to. In format of "group/version". Required.
    api_version: Any = None
    # kind is the API kind the resources belong to. Required.
    kind: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec_Validations:
    # Expression is the CEL expression that is evaluated for each admission request. It must return a boolean value, and may reference variables defined in the policy's spec.variables. (AI-inferred)
    expression: Any = None
    # An optional human-readable message that is displayed when the validation expression evaluates to false. This message is returned to the client as part of the admission denial response. (AI-inferred)
    message: Any = None
    # A CEL expression that produces a custom validation failure message. The expression must evaluate to a string; if it produces an error, the validation fails with that error message. (AI-inferred)
    message_expression: Any = None
    # The machine-readable reason returned to the request when the validation rule evaluates to false. Must be a valid StatusReason; defaults to 'Invalid'. (AI-inferred)
    reason: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Spec:
    # auditAnnotations contains CEL expressions which are used to produce audit annotations for the audit event of the API request. validations and auditAnnotations may not both be empty; a least one of validations or auditAnnotations is required.
    audit_annotations: Any = None
    # failurePolicy defines how to handle failures for the admission policy. Failures can occur from CEL expression parse errors, type check errors, runtime errors and invalid or mis-configured policy definitions or bindings. A policy is invalid if spec.paramKind refers to a non-existent Kind. A binding is invalid if spec.paramRef.name refers to a non-existent resource. failurePolicy does not define how validations that evaluate to false are handled. When failurePolicy is set to Fail, ValidatingAdmissionPolicyBinding validationActions define how failures are enforced. Allowed values are Ignore or Fail. Defaults to Fail.
    failure_policy: Any = None
    # matchConditions is a list of conditions that must be met for a request to be validated. Match conditions filter requests that have already been matched by the rules, namespaceSelector, and objectSelector. An empty list of matchConditions matches all requests. There are a maximum of 64 match conditions allowed. If a parameter object is provided, it can be accessed via the `params` handle in the same manner as validation expressions. The exact matching logic is (in order): 1. If ANY matchCondition evaluates to FALSE, the policy is skipped. 2. If ALL matchConditions evaluate to TRUE, the policy is evaluated. 3. If any matchCondition evaluates to an error (but none are FALSE): - If failurePolicy=Fail, reject the request - If failurePolicy=Ignore, the policy is skipped
    match_conditions: Any = None
    # MatchResources decides whether to run the admission control policy on an object based on whether it meets the match criteria. The exclude rules take precedence over include rules (if a resource matches both, it is excluded)
    match_constraints: Any = None
    # ParamKind is a tuple of Group Kind and Version.
    param_kind: Any = None
    # validations contain CEL expressions which is used to apply the validation. Validations and AuditAnnotations may not both be empty; a minimum of one Validations or AuditAnnotations is required.
    validations: Any = None
    # variables contain definitions of variables that can be used in composition of other expressions. Each variable is defined as a named CEL expression. The variables defined here will be available under `variables` in other expressions of the policy except MatchConditions because MatchConditions are evaluated before the rest of the policy. The expression of a variable can refer to other variables defined earlier in the list but not those after. Thus, Variables must be sorted by the order of first appearance and acyclic.
    variables: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Status_Conditions:
    # The last time the condition transitioned from one status to another. This should reflect when the underlying condition changed, typically represented as a timestamp string. (AI-inferred)
    last_transition_time: Any = None
    # A human-readable message that provides additional details about the current condition, including information about the last transition. (AI-inferred)
    message: Any = None
    # The generation of the ValidatingAdmissionPolicy that was last processed by the controller, used to determine whether the status reflects the latest spec. (AI-inferred)
    observed_generation: Any = None
    # A machine-readable, CamelCase reason for the condition's last transition. This provides a stable identifier for the condition state, complementing the human-readable message. (AI-inferred)
    reason: Any = None
    # The status of the condition, indicating whether the condition is True, False, or Unknown. (AI-inferred)
    status: Any = None
    # Type is a string that identifies the condition and distinguishes it from other conditions in the status.conditions list. (AI-inferred)
    type: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Status_TypeChecking_ExpressionWarnings:
    # The field path (as a JSON pointer) within the resource that the warning message refers to, identifying which expression or sub-field caused the type-checking warning. (AI-inferred)
    field_ref: Any = None
    # The warning message attached to the expression, describing the type-checking issue identified in the validating admission policy. (AI-inferred)
    warning: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Status_TypeChecking:
    # expressionWarnings contains the type checking warnings for each expression.
    expression_warnings: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicy_Status:
    # conditions represent the latest available observations of a policy's current state.
    conditions: Any = None
    # observedGeneration is the generation observed by the controller.
    observed_generation: Any = None
    # TypeChecking contains results of type checking the expressions in the ValidatingAdmissionPolicy
    type_checking: Any = None

_ValidatingAdmissionPolicy_Metadata_ManagedFieldsFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "fields_type": ubx.FieldSpec(wire_name="fields_type"),
    "fields_v1": ubx.FieldSpec(wire_name="fields_v1"),
    "manager": ubx.FieldSpec(wire_name="manager"),
    "operation": ubx.FieldSpec(wire_name="operation"),
    "subresource": ubx.FieldSpec(wire_name="subresource"),
    "time": ubx.FieldSpec(wire_name="time"),
}

_ValidatingAdmissionPolicy_Metadata_OwnerReferencesFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "block_owner_deletion": ubx.FieldSpec(wire_name="block_owner_deletion"),
    "controller": ubx.FieldSpec(wire_name="controller"),
    "kind": ubx.FieldSpec(wire_name="kind"),
    "name": ubx.FieldSpec(wire_name="name"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_ValidatingAdmissionPolicy_MetadataFields = {
    "annotations": ubx.FieldSpec(wire_name="annotations"),
    "creation_timestamp": ubx.FieldSpec(wire_name="creation_timestamp"),
    "deletion_grace_period_seconds": ubx.FieldSpec(wire_name="deletion_grace_period_seconds"),
    "deletion_timestamp": ubx.FieldSpec(wire_name="deletion_timestamp"),
    "finalizers": ubx.FieldSpec(wire_name="finalizers"),
    "generate_name": ubx.FieldSpec(wire_name="generate_name"),
    "generation": ubx.FieldSpec(wire_name="generation"),
    "labels": ubx.FieldSpec(wire_name="labels"),
    "managed_fields": ubx.FieldSpec(
        wire_name="managed_fields",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Metadata_ManagedFieldsFields,
    ),
    "name": ubx.FieldSpec(wire_name="name"),
    "namespace": ubx.FieldSpec(wire_name="namespace"),
    "owner_references": ubx.FieldSpec(
        wire_name="owner_references",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Metadata_OwnerReferencesFields,
    ),
    "resource_version": ubx.FieldSpec(wire_name="resource_version"),
    "self_link": ubx.FieldSpec(wire_name="self_link"),
    "uid": ubx.FieldSpec(wire_name="uid"),
}

_ValidatingAdmissionPolicy_Spec_AuditAnnotationsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "value_expression": ubx.FieldSpec(wire_name="value_expression"),
}

_ValidatingAdmissionPolicy_Spec_MatchConditionsFields = {
    "expression": ubx.FieldSpec(wire_name="expression"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_ValidatingAdmissionPolicy_Spec_MatchConstraints_ExcludeResourceRulesFields = {
    "api_groups": ubx.FieldSpec(wire_name="api_groups"),
    "api_versions": ubx.FieldSpec(wire_name="api_versions"),
    "operations": ubx.FieldSpec(wire_name="operations"),
    "resource_names": ubx.FieldSpec(wire_name="resource_names"),
    "resources": ubx.FieldSpec(wire_name="resources"),
    "scope": ubx.FieldSpec(wire_name="scope"),
}

_ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelector_MatchExpressionsFields = {
    "key": ubx.FieldSpec(wire_name="key"),
    "operator": ubx.FieldSpec(wire_name="operator"),
    "values": ubx.FieldSpec(wire_name="values"),
}

_ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelectorFields = {
    "match_expressions": ubx.FieldSpec(
        wire_name="match_expressions",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelector_MatchExpressionsFields,
    ),
    "match_labels": ubx.FieldSpec(wire_name="match_labels"),
}

_ValidatingAdmissionPolicy_Spec_MatchConstraintsFields = {
    "exclude_resource_rules": ubx.FieldSpec(
        wire_name="exclude_resource_rules",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraints_ExcludeResourceRulesFields,
    ),
    "match_policy": ubx.FieldSpec(wire_name="match_policy"),
    "namespace_selector": ubx.FieldSpec(
        wire_name="namespace_selector",
        kind="object",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelectorFields,
    ),
    "object_selector": ubx.FieldSpec(
        wire_name="object_selector",
        kind="object",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraints_NamespaceSelectorFields,
    ),
    "resource_rules": ubx.FieldSpec(
        wire_name="resource_rules",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraints_ExcludeResourceRulesFields,
    ),
}

_ValidatingAdmissionPolicy_Spec_ParamKindFields = {
    "api_version": ubx.FieldSpec(wire_name="api_version"),
    "kind": ubx.FieldSpec(wire_name="kind"),
}

_ValidatingAdmissionPolicy_Spec_ValidationsFields = {
    "expression": ubx.FieldSpec(wire_name="expression"),
    "message": ubx.FieldSpec(wire_name="message"),
    "message_expression": ubx.FieldSpec(wire_name="message_expression"),
    "reason": ubx.FieldSpec(wire_name="reason"),
}

_ValidatingAdmissionPolicy_SpecFields = {
    "audit_annotations": ubx.FieldSpec(
        wire_name="audit_annotations",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_AuditAnnotationsFields,
    ),
    "failure_policy": ubx.FieldSpec(wire_name="failure_policy"),
    "match_conditions": ubx.FieldSpec(
        wire_name="match_conditions",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConditionsFields,
    ),
    "match_constraints": ubx.FieldSpec(
        wire_name="match_constraints",
        kind="object",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConstraintsFields,
    ),
    "param_kind": ubx.FieldSpec(
        wire_name="param_kind",
        kind="object",
        fields=_ValidatingAdmissionPolicy_Spec_ParamKindFields,
    ),
    "validations": ubx.FieldSpec(
        wire_name="validations",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_ValidationsFields,
    ),
    "variables": ubx.FieldSpec(
        wire_name="variables",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Spec_MatchConditionsFields,
    ),
}

_ValidatingAdmissionPolicy_Status_ConditionsFields = {
    "last_transition_time": ubx.FieldSpec(wire_name="last_transition_time"),
    "message": ubx.FieldSpec(wire_name="message"),
    "observed_generation": ubx.FieldSpec(wire_name="observed_generation"),
    "reason": ubx.FieldSpec(wire_name="reason"),
    "status": ubx.FieldSpec(wire_name="status"),
    "type": ubx.FieldSpec(wire_name="type"),
}

_ValidatingAdmissionPolicy_Status_TypeChecking_ExpressionWarningsFields = {
    "field_ref": ubx.FieldSpec(wire_name="field_ref"),
    "warning": ubx.FieldSpec(wire_name="warning"),
}

_ValidatingAdmissionPolicy_Status_TypeCheckingFields = {
    "expression_warnings": ubx.FieldSpec(
        wire_name="expression_warnings",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Status_TypeChecking_ExpressionWarningsFields,
    ),
}

_ValidatingAdmissionPolicy_StatusFields = {
    "conditions": ubx.FieldSpec(
        wire_name="conditions",
        kind="list",
        fields=_ValidatingAdmissionPolicy_Status_ConditionsFields,
    ),
    "observed_generation": ubx.FieldSpec(wire_name="observed_generation"),
    "type_checking": ubx.FieldSpec(
        wire_name="type_checking",
        kind="object",
        fields=_ValidatingAdmissionPolicy_Status_TypeCheckingFields,
    ),
}

@dataclasses.dataclass
class ValidatingAdmissionPolicyConfig:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ValidatingAdmissionPolicySpec is the specification of the desired behavior of the AdmissionPolicy.
    spec: Any = None
    # ValidatingAdmissionPolicyStatus represents the status of an admission validation policy.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

@dataclasses.dataclass
class ValidatingAdmissionPolicyAttrs:
    # APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    api_version: Any = None
    # Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    kind: Any = None
    # ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    metadata: Any = None
    # ValidatingAdmissionPolicySpec is the specification of the desired behavior of the AdmissionPolicy.
    spec: Any = None
    # ValidatingAdmissionPolicyStatus represents the status of an admission validation policy.
    status: Any = None
    # path parameter, not part of the API's own resource representation
    name: Any = None

ValidatingAdmissionPolicy = ubx.ResourceBinding(
    wire_type="kubernetes_admissionregistration_validating_admission_policy",
    fields={
        "api_version": ubx.FieldSpec(wire_name="api_version"),
        "kind": ubx.FieldSpec(wire_name="kind"),
        "metadata": ubx.FieldSpec(
            wire_name="metadata",
            kind="object",
            fields=_ValidatingAdmissionPolicy_MetadataFields,
        ),
        "spec": ubx.FieldSpec(
            wire_name="spec",
            kind="object",
            fields=_ValidatingAdmissionPolicy_SpecFields,
        ),
        "status": ubx.FieldSpec(
            wire_name="status",
            kind="object",
            fields=_ValidatingAdmissionPolicy_StatusFields,
        ),
        "name": ubx.FieldSpec(wire_name="name"),
    },
)
