// Code generated by `ubx sdk gen` from kubernetes_scheduling_pod_group. DO NOT EDIT.
package scheduling

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type PodGroup_Metadata_ManagedFields struct {
	ApiVersion any
	FieldsType any
	FieldsV1 any
	Manager any
	Operation any
	Subresource any
	Time any
}

type PodGroup_Metadata_OwnerReferences struct {
	ApiVersion any
	BlockOwnerDeletion any
	Controller any
	Kind any
	Name any
	Uid any
}

type PodGroup_Metadata struct {
	// Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
	Annotations any
	// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
	CreationTimestamp any
	// Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
	DeletionGracePeriodSeconds any
	// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers.
	DeletionTimestamp any
	// Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
	Finalizers any
	// GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
	GenerateName any
	// A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
	Generation any
	// Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
	Labels any
	// ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
	ManagedFields any
	// Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
	Name any
	// Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
	Namespace any
	// List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
	OwnerReferences any
	// An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
	ResourceVersion any
	// Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
	SelfLink any
	// UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
	Uid any
}

type PodGroup_Spec_DisruptionMode struct {
	// AllDisruptionMode specifies that children can only be disrupted together.
	All any
	// SingleDisruptionMode specifies that children can be disrupted independently.
	Single any
}

type PodGroup_Spec_ResourceClaims struct {
	Name any
	ResourceClaimName any
	ResourceClaimTemplateName any
}

type PodGroup_Spec_SchedulingConstraints_Topology struct {
	Key any
}

type PodGroup_Spec_SchedulingConstraints struct {
	// topology defines the topology constraints for the pod group. Currently only a single topology constraint can be specified. This may change in the future.
	Topology any
}

type PodGroup_Spec_SchedulingPolicy_Gang struct {
	// minCount is the minimum number of pods that must be schedulable or scheduled at the same time for the scheduler to admit the entire group. It must be a positive integer. This field is mutable to support workload scaling. Note that the scheduler operates on an eventually consistent model. Updates to minCount may not be immediately reflected in scheduling decisions due to propagation delays. If minCount is updated while a scheduling cycle is in progress for that group, the new value may not take effect until the next cycle. Moreover, minCount is only enforced during scheduling, meaning that modifications to this field do not affect already-scheduled pods, applying only to those evaluated in future cycles.
	MinCount any
}

type PodGroup_Spec_SchedulingPolicy struct {
	// BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used.
	Basic any
	// GangSchedulingPolicy defines the parameters for gang scheduling.
	Gang any
}

type PodGroup_Spec_WorkloadRef struct {
	// templateName is the name of a template within the Workload object that was used to create a pod group. It must be a DNS label. This field is required.
	TemplateName any
	// workloadName is the name of the Workload object that contains a template that was used when creating a pod group. It must be a DNS name. This field is required.
	WorkloadName any
}

type PodGroup_Spec struct {
	// DisruptionMode defines how individual entities within a group can be disrupted. Exactly one mode can be set.
	DisruptionMode any
	// parentCompositePodGroupName contains the name of the parent composite pod group within the same namespace as this pod group. If it's nil, then this pod group is a root of a workload's hierarchy. This field is used only when the CompositePodGroup feature gate is enabled. This field is immutable.
	ParentCompositePodGroupName any
	// preemptionPolicy is the Policy for preempting pods/podgroups with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset. When Priority Admission Controller is enabled, it populates this field from PriorityClassName, and defaults to PreemptLowerPriority if value is unset in PriorityClass. This field is immutable. This field is available only when the PodGroupPreemptionPolicy feature gate is enabled.
	PreemptionPolicy any
	// priority is the value of priority of this pod group. Various system components use this field to find the priority of the pod group. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. This field is immutable.
	Priority any
	// priorityClassName defines the priority that should be considered when scheduling this pod group. Controllers are expected to fill this field by copying it from a PodGroupTemplate. Otherwise, it is validated and resolved similarly to the PriorityClassName on PodGroupTemplate (i.e. if no priority class is specified, admission control can set this to the global default priority class if it exists. Otherwise, the pod group's priority will be zero). This field is immutable.
	PriorityClassName any
	// resourceClaims defines which ResourceClaims may be shared among Pods in the group. Pods consume the devices allocated to a PodGroup's claim by defining a claim in its own Spec.ResourceClaims that matches the PodGroup's claim exactly. The claim must have the same name and refer to the same ResourceClaim or ResourceClaimTemplate. This is a beta-level field and requires that the DRAWorkloadResourceClaims feature gate is enabled. This field is immutable.
	ResourceClaims any
	// PodGroupSchedulingConstraints defines scheduling constraints (e.g. topology) for a PodGroup.
	SchedulingConstraints any
	// PodGroupSchedulingPolicy defines the scheduling configuration for a PodGroup. Exactly one policy must be set. The policy is chosen at creation time by setting either the Basic or Gang field. The PodGroup may not change policy after creation. Fields within chosen policy may be updated after creation when their individual fields allow it.
	SchedulingPolicy any
	// WorkloadReference references the Workload object together with the template that was used to create a particular PodGroup.
	WorkloadRef any
}

type PodGroup_Status_Conditions struct {
	LastTransitionTime any
	Message any
	ObservedGeneration any
	Reason any
	Status any
	Type any
}

type PodGroup_Status_ResourceClaimStatuses struct {
	Name any
	ResourceClaimName any
}

type PodGroup_Status struct {
	// conditions represent the latest observations of the PodGroup's state. Known condition types: - "PodGroupInitiallyScheduled": Indicates whether the scheduling requirement has been satisfied. Once this condition transitions to True, it serves as a terminal state and will never revert to False, even if pods are subsequently evicted and group constraints are no longer met. - "DisruptionTarget": Indicates whether the PodGroup is about to be terminated due to disruption such as preemption. Known reasons for the PodGroupInitiallyScheduled condition: - "Unschedulable": The PodGroup cannot be scheduled due to resource constraints, affinity/anti-affinity rules, or insufficient capacity for the gang. - "SchedulerError": The PodGroup cannot be scheduled due to some internal error that happened during scheduling, for example due to nodeAffinity parsing errors. Known reasons for the DisruptionTarget condition: - "PreemptionByScheduler": The PodGroup was preempted by the scheduler to make room for higher-priority PodGroups or Pods.
	Conditions any
	// resourceClaimStatuses is status of resource claims.
	ResourceClaimStatuses any
}

type PodGroupConfig struct {
}

type PodGroupAttrs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion any
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind any
	// ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
	Metadata any
	// PodGroupSpec defines the desired state of a PodGroup.
	Spec any
	// PodGroupStatus represents information about the status of a pod group.
	Status any
}

var PodGroup = ubx.DataSourceBinding{
	WireType: "kubernetes_scheduling_pod_group",
	Fields: ubx.FieldMap{
	},
}
