// Code generated by `ubx sdk gen` from kubernetes_apiextensions_custom_resource_definition. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CustomResourceDefinition_Metadata_ManagedFields {
  apiVersion?: string | Computed<string>;
  fieldsType?: string | Computed<string>;
  fieldsV1?: unknown | Computed<unknown>;
  manager?: string | Computed<string>;
  operation?: string | Computed<string>;
  subresource?: string | Computed<string>;
  time?: string | Computed<string>;
}

export interface CustomResourceDefinition_Metadata_OwnerReferences {
  apiVersion?: string | Computed<string>;
  blockOwnerDeletion?: boolean | Computed<boolean>;
  controller?: boolean | Computed<boolean>;
  kind?: string | Computed<string>;
  name?: string | Computed<string>;
  uid?: string | Computed<string>;
}

export interface CustomResourceDefinition_Metadata {
  /** Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations */
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  /** Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers. */
  creationTimestamp?: string | Computed<string>;
  /** Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only. */
  deletionGracePeriodSeconds?: number | Computed<number>;
  /** Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON. Wrappers are provided for many of the factory methods that the time package offers. */
  deletionTimestamp?: string | Computed<string>;
  /** Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order. Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list. */
  finalizers?: string[] | Computed<string[]>;
  /** GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server. If this field is specified and the generated name exists, the server will return a 409. Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency */
  generateName?: string | Computed<string>;
  /** A sequence number representing a specific generation of the desired state. Populated by the system. Read-only. */
  generation?: number | Computed<number>;
  /** Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels */
  labels?: Record<string, string> | Computed<Record<string, string>>;
  /** ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object. */
  managedFields?: CustomResourceDefinition_Metadata_ManagedFields[] | Computed<CustomResourceDefinition_Metadata_ManagedFields[]>;
  /** Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
  name?: string | Computed<string>;
  /** Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty. Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
  namespace?: string | Computed<string>;
  /** List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller. */
  ownerReferences?: CustomResourceDefinition_Metadata_OwnerReferences[] | Computed<CustomResourceDefinition_Metadata_OwnerReferences[]>;
  /** An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources. Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency */
  resourceVersion?: string | Computed<string>;
  /** Deprecated: selfLink is a legacy read-only field that is no longer populated by the system. */
  selfLink?: string | Computed<string>;
  /** UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations. Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids */
  uid?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig_Service {
  /** name is the name of the service. Required */
  name: string | Computed<string>;
  /** namespace is the namespace of the service. Required */
  namespace: string | Computed<string>;
  /** path is an optional URL path at which the webhook will be contacted. */
  path?: string | Computed<string>;
  /** port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility. */
  port?: number | Computed<number>;
}

export interface CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig {
  /** caBundle is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used. */
  caBundle?: string | Computed<string>;
  /** ServiceReference holds a reference to Service.legacy.k8s.io */
  service?: CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig_Service | Computed<CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig_Service>;
  /** url gives the location of the webhook, in standard URL form (`scheme://host:port/path`). Exactly one of `url` or `service` must be specified. The `host` should not refer to a service running in the cluster; use the `service` field instead. The host might be resolved via external DNS in some apiservers (e.g., `kube-apiserver` cannot resolve in-cluster DNS as that would be a layering violation). `host` may also be an IP address. Please note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this webhook. Such installs are likely to be non-portable, i.e., not easy to turn up in a new cluster. The scheme must be "https"; the URL must begin with "https://". A path is optional, and if present may be any string permissible in a URL. You may use the path to pass an arbitrary string to the webhook, for example, a cluster identifier. Attempting to use a user or basic auth e.g. "user:password@" is not allowed. Fragments ("#...") and query parameters ("?...") are not allowed, either. */
  url?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Conversion_Webhook {
  /** WebhookClientConfig contains the information to make a TLS connection with the webhook. */
  clientConfig?: CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig | Computed<CustomResourceDefinition_Spec_Conversion_Webhook_ClientConfig>;
  /** conversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail. */
  conversionReviewVersions: string[] | Computed<string[]>;
}

export interface CustomResourceDefinition_Spec_Conversion {
  /** strategy specifies how custom resources are converted between versions. Allowed values are: - `"None"`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `"Webhook"`: API Server will call to an external webhook to do the conversion. Additional information is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set. */
  strategy: string | Computed<string>;
  /** WebhookConversion describes how to call a conversion webhook */
  webhook?: CustomResourceDefinition_Spec_Conversion_Webhook | Computed<CustomResourceDefinition_Spec_Conversion_Webhook>;
}

export interface CustomResourceDefinition_Spec_Names {
  /** categories is a list of grouped resources this custom resource belongs to (e.g. 'all'). This is published in API discovery documents, and used by clients to support invocations like `kubectl get all`. */
  categories?: string[] | Computed<string[]>;
  /** kind is the serialized kind of the resource. It is normally CamelCase and singular. Custom resource instances will use this value as the `kind` attribute in API calls. */
  kind: string | Computed<string>;
  /** listKind is the serialized kind of the list for this resource. Defaults to "`kind`List". */
  listKind?: string | Computed<string>;
  /** plural is the plural name of the resource to serve. The custom resources are served under `/apis/<group>/<version>/.../<plural>`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`). Must be all lowercase. */
  plural: string | Computed<string>;
  /** shortNames are short names for the resource, exposed in API discovery documents, and used by clients to support invocations like `kubectl get <shortname>`. It must be all lowercase. */
  shortNames?: string[] | Computed<string[]>;
  /** singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`. */
  singular?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_AdditionalPrinterColumns {
  description?: string | Computed<string>;
  format?: string | Computed<string>;
  jsonPath?: string | Computed<string>;
  name?: string | Computed<string>;
  priority?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf {
}

export interface CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_ExternalDocs {
  description?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_XKubernetesValidations {
  fieldPath?: string | Computed<string>;
  message?: string | Computed<string>;
  messageExpression?: string | Computed<string>;
  optionalOldSelf?: boolean | Computed<boolean>;
  reason?: string | Computed<string>;
  rule?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema {
  additionalItems?: unknown | Computed<unknown>;
  additionalProperties?: unknown | Computed<unknown>;
  allOf?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[] | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[]>;
  anyOf?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[] | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[]>;
  default?: unknown | Computed<unknown>;
  definitions?: Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf> | Computed<Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf>>;
  dependencies?: Record<string, unknown> | Computed<Record<string, unknown>>;
  description?: string | Computed<string>;
  enum?: unknown[] | Computed<unknown[]>;
  example?: unknown | Computed<unknown>;
  exclusiveMaximum?: boolean | Computed<boolean>;
  exclusiveMinimum?: boolean | Computed<boolean>;
  externalDocs?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_ExternalDocs | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_ExternalDocs>;
  format?: string | Computed<string>;
  id?: string | Computed<string>;
  items?: unknown | Computed<unknown>;
  maxItems?: number | Computed<number>;
  maxLength?: number | Computed<number>;
  maxProperties?: number | Computed<number>;
  maximum?: number | Computed<number>;
  minItems?: number | Computed<number>;
  minLength?: number | Computed<number>;
  minProperties?: number | Computed<number>;
  minimum?: number | Computed<number>;
  multipleOf?: number | Computed<number>;
  not?: unknown | Computed<unknown>;
  nullable?: boolean | Computed<boolean>;
  oneOf?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[] | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf[]>;
  pattern?: string | Computed<string>;
  patternProperties?: Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf> | Computed<Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf>>;
  properties?: Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf> | Computed<Record<string, CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_AllOf>>;
  required?: string[] | Computed<string[]>;
  title?: string | Computed<string>;
  type?: string | Computed<string>;
  uniqueItems?: boolean | Computed<boolean>;
  xKubernetesEmbeddedResource?: boolean | Computed<boolean>;
  xKubernetesIntOrString?: boolean | Computed<boolean>;
  xKubernetesListMapKeys?: string[] | Computed<string[]>;
  xKubernetesListType?: string | Computed<string>;
  xKubernetesMapType?: string | Computed<string>;
  xKubernetesPreserveUnknownFields?: boolean | Computed<boolean>;
  xKubernetesValidations?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_XKubernetesValidations[] | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema_XKubernetesValidations[]>;
}

export interface CustomResourceDefinition_Spec_Versions_Schema {
  openApiv3Schema?: CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema | Computed<CustomResourceDefinition_Spec_Versions_Schema_OpenApiv3Schema>;
}

export interface CustomResourceDefinition_Spec_Versions_SelectableFields {
  jsonPath?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_Subresources_Scale {
  labelSelectorPath?: string | Computed<string>;
  specReplicasPath?: string | Computed<string>;
  statusReplicasPath?: string | Computed<string>;
}

export interface CustomResourceDefinition_Spec_Versions_Subresources {
  scale?: CustomResourceDefinition_Spec_Versions_Subresources_Scale | Computed<CustomResourceDefinition_Spec_Versions_Subresources_Scale>;
  status?: unknown | Computed<unknown>;
}

export interface CustomResourceDefinition_Spec_Versions {
  additionalPrinterColumns?: CustomResourceDefinition_Spec_Versions_AdditionalPrinterColumns[] | Computed<CustomResourceDefinition_Spec_Versions_AdditionalPrinterColumns[]>;
  deprecated?: boolean | Computed<boolean>;
  deprecationWarning?: string | Computed<string>;
  name?: string | Computed<string>;
  schema?: CustomResourceDefinition_Spec_Versions_Schema | Computed<CustomResourceDefinition_Spec_Versions_Schema>;
  selectableFields?: CustomResourceDefinition_Spec_Versions_SelectableFields[] | Computed<CustomResourceDefinition_Spec_Versions_SelectableFields[]>;
  served?: boolean | Computed<boolean>;
  storage?: boolean | Computed<boolean>;
  subresources?: CustomResourceDefinition_Spec_Versions_Subresources | Computed<CustomResourceDefinition_Spec_Versions_Subresources>;
}

export interface CustomResourceDefinition_Spec {
  /** CustomResourceConversion describes how to convert different versions of a CR. */
  conversion?: CustomResourceDefinition_Spec_Conversion | Computed<CustomResourceDefinition_Spec_Conversion>;
  /** group is the API group of the defined custom resource. The custom resources are served under `/apis/<group>/...`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`). */
  group: string | Computed<string>;
  /** CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition */
  names: CustomResourceDefinition_Spec_Names | Computed<CustomResourceDefinition_Spec_Names>;
  /** preserveUnknownFields indicates that object fields which are not specified in the OpenAPI schema should be preserved when persisting to storage. apiVersion, kind, metadata and known fields inside metadata are always preserved. This field is deprecated in favor of setting `x-preserve-unknown-fields` to true in `spec.versions[*].schema.openAPIV3Schema`. See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning for details. */
  preserveUnknownFields?: boolean | Computed<boolean>;
  /** scope indicates whether the defined custom resource is cluster- or namespace-scoped. Allowed values are `Cluster` and `Namespaced`. */
  scope: string | Computed<string>;
  /** versions is the list of all API versions of the defined custom resource. Version names are used to compute the order in which served versions are listed in API discovery. If the version string is "kube-like", it will sort above non "kube-like" version strings, which are ordered lexicographically. "Kube-like" versions start with a "v", then are followed by a number (the major version), then optionally the string "alpha" or "beta" and another number (the minor version). These are sorted first by GA > beta > alpha (where GA is a version with no suffix such as beta or alpha), and then by comparing major version, then minor version. An example sorted list of versions: v10, v2, v1, v11beta2, v10beta3, v3beta1, v12alpha1, v11alpha2, foo1, foo10. */
  versions: CustomResourceDefinition_Spec_Versions[] | Computed<CustomResourceDefinition_Spec_Versions[]>;
}

export interface CustomResourceDefinition_Status_Conditions {
  lastTransitionTime?: string | Computed<string>;
  message?: string | Computed<string>;
  observedGeneration?: number | Computed<number>;
  reason?: string | Computed<string>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface CustomResourceDefinition_Status {
  /** CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition */
  acceptedNames?: CustomResourceDefinition_Spec_Names | Computed<CustomResourceDefinition_Spec_Names>;
  /** conditions indicate state for particular aspects of a CustomResourceDefinition */
  conditions?: CustomResourceDefinition_Status_Conditions[] | Computed<CustomResourceDefinition_Status_Conditions[]>;
  /** The generation observed by the CRD controller. */
  observedGeneration?: number | Computed<number>;
  /** storedVersions lists all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so a migration controller can finish a migration to another version (ensuring no old objects are left in storage), and then remove the rest of the versions from this list. Versions may not be removed from `spec.versions` while they exist in this list. */
  storedVersions?: string[] | Computed<string[]>;
}

export interface CustomResourceDefinitionConfig {
}

export interface CustomResourceDefinitionAttrs {
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
  apiVersion: string;
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
  kind: string;
  /** ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create. */
  metadata: CustomResourceDefinition_Metadata;
  /** CustomResourceDefinitionSpec describes how a user wants their resource to appear */
  spec: CustomResourceDefinition_Spec;
  /** CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition */
  status: CustomResourceDefinition_Status;
}

export const CustomResourceDefinition: DataSourceBinding<CustomResourceDefinitionConfig, CustomResourceDefinitionAttrs> = {
  wireType: "kubernetes_apiextensions_custom_resource_definition",
  fields: {
  },
};
