// Code generated by `ubx sdk gen` from kubernetes_cron_job_v1. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface JobV1_Metadata {
  annotations: Record<string, string>;
  generateName: string;
  generation: number;
  labels: Record<string, string>;
  name: string;
  namespace: string;
  resourceVersion: string;
  uid: string;
}

export interface JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnExitCodes {
  containerName: string;
  operator: string;
  values: number[];
}

export interface JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnPodCondition {
  status: string;
  type: string;
}

export interface JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule {
  action: string;
  onExitCodes: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnExitCodes[];
  onPodCondition: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnPodCondition[];
}

export interface JobV1_Spec_JobTemplate_Spec_PodFailurePolicy {
  rule: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule[];
}

export interface JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressions {
  key: string;
  operator: string;
  values: string[];
}

export interface JobV1_Spec_JobTemplate_Spec_Selector {
  matchLabels: Record<string, string>;
  matchExpressions: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressions[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Metadata {
  annotations: Record<string, string>;
  generateName: string;
  generation: number;
  labels: Record<string, string>;
  name: string;
  resourceVersion: string;
  uid: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference {
  matchExpressions: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressions[];
  matchFields: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressions[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  weight: number;
  preference: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution {
  nodeSelectorTerm: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_Preference[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity {
  preferredDuringSchedulingIgnoredDuringExecution: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution[];
  requiredDuringSchedulingIgnoredDuringExecution: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecution[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm {
  namespaces: string[];
  topologyKey: string;
  labelSelector: JobV1_Spec_JobTemplate_Spec_Selector[];
  namespaceSelector: JobV1_Spec_JobTemplate_Spec_Selector[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution {
  weight: number;
  podAffinityTerm: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity {
  preferredDuringSchedulingIgnoredDuringExecution: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution[];
  requiredDuringSchedulingIgnoredDuringExecution: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTerm[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity {
  nodeAffinity: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity[];
  podAffinity: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity[];
  podAntiAffinity: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRef {
  key: string;
  name: string;
  optional: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRef {
  apiVersion: string;
  fieldPath: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRef {
  containerName: string;
  divisor: string;
  resource: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom {
  configMapKeyRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRef[];
  fieldRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRef[];
  resourceFieldRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRef[];
  secretKeyRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env {
  name: string;
  value: string;
  valueFrom: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRef {
  name: string;
  optional: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom {
  prefix: string;
  configMapRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRef[];
  secretRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_Exec {
  command: string[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeader {
  name: string;
  value: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet {
  host: string;
  path: string;
  port: string;
  scheme: string;
  httpHeader: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeader[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocket {
  port: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart {
  exec: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_Exec[];
  httpGet: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet[];
  tcpSocket: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocket[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle {
  postStart: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart[];
  preStop: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe_Grpc {
  port: number;
  service: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe {
  failureThreshold: number;
  initialDelaySeconds: number;
  periodSeconds: number;
  successThreshold: number;
  timeoutSeconds: number;
  exec: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_Exec[];
  grpc: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe_Grpc[];
  httpGet: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet[];
  tcpSocket: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocket[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Port {
  containerPort: number;
  hostIp: string;
  hostPort: number;
  name: string;
  protocol: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Resources {
  limits: Record<string, string>;
  requests: Record<string, string>;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_Capabilities {
  add: string[];
  drop: string[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptions {
  level: string;
  role: string;
  type: string;
  user: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfile {
  localhostProfile: string;
  type: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext {
  allowPrivilegeEscalation: boolean;
  privileged: boolean;
  readOnlyRootFilesystem: boolean;
  runAsGroup: string;
  runAsNonRoot: boolean;
  runAsUser: string;
  capabilities: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_Capabilities[];
  seLinuxOptions: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptions[];
  seccompProfile: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfile[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeDevice {
  devicePath: string;
  name: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeMount {
  mountPath: string;
  mountPropagation: string;
  name: string;
  readOnly: boolean;
  subPath: string;
  subPathExpr: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Container {
  args: string[];
  command: string[];
  image: string;
  imagePullPolicy: string;
  name: string;
  restartPolicy: string;
  stdin: boolean;
  stdinOnce: boolean;
  terminationMessagePath: string;
  terminationMessagePolicy: string;
  tty: boolean;
  workingDir: string;
  env: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env[];
  envFrom: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom[];
  lifecycle: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle[];
  livenessProbe: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe[];
  port: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Port[];
  readinessProbe: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe[];
  resources: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Resources[];
  securityContext: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext[];
  startupProbe: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe[];
  volumeDevice: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeDevice[];
  volumeMount: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeMount[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_DnsConfig {
  nameservers: string[];
  searches: string[];
  option: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeader[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_HostAliases {
  hostnames: string[];
  ip: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecrets {
  name: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_ReadinessGate {
  conditionType: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext_WindowsOptions {
  gmsaCredentialSpec: string;
  gmsaCredentialSpecName: string;
  hostProcess: boolean;
  runAsUsername: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext {
  fsGroup: string;
  fsGroupChangePolicy: string;
  runAsGroup: string;
  runAsNonRoot: boolean;
  runAsUser: string;
  supplementalGroups: number[];
  seLinuxOptions: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptions[];
  seccompProfile: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfile[];
  sysctl: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeader[];
  windowsOptions: JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext_WindowsOptions[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Toleration {
  effect: string;
  key: string;
  operator: string;
  tolerationSeconds: string;
  value: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_TopologySpreadConstraint {
  matchLabelKeys: string[];
  maxSkew: number;
  minDomains: number;
  nodeAffinityPolicy: string;
  nodeTaintsPolicy: string;
  topologyKey: string;
  whenUnsatisfiable: string;
  labelSelector: JobV1_Spec_JobTemplate_Spec_Selector[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AwsElasticBlockStore {
  fsType: string;
  partition: number;
  readOnly: boolean;
  volumeId: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureDisk {
  cachingMode: string;
  dataDiskUri: string;
  diskName: string;
  fsType: string;
  kind: string;
  readOnly: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureFile {
  readOnly: boolean;
  secretName: string;
  secretNamespace: string;
  shareName: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRef {
  name: string;
  namespace: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs {
  monitors: string[];
  path: string;
  readOnly: boolean;
  secretFile: string;
  user: string;
  secretRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Cinder {
  fsType: string;
  readOnly: boolean;
  volumeId: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_Items {
  key: string;
  mode: string;
  path: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap {
  defaultMode: string;
  name: string;
  optional: boolean;
  items: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_Items[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Csi {
  driver: string;
  fsType: string;
  readOnly: boolean;
  volumeAttributes: Record<string, string>;
  nodePublishSecretRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecrets[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_Items {
  mode: string;
  path: string;
  fieldRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRef[];
  resourceFieldRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi {
  defaultMode: string;
  items: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_Items[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EmptyDir {
  medium: string;
  sizeLimit: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_Metadata {
  annotations: Record<string, string>;
  labels: Record<string, string>;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_Spec {
  accessModes: string[];
  storageClassName: string;
  volumeMode: string;
  volumeName: string;
  resources: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Resources[];
  selector: JobV1_Spec_JobTemplate_Spec_Selector[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate {
  metadata: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_Metadata[];
  spec: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_Spec[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral {
  volumeClaimTemplate: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Fc {
  fsType: string;
  lun: number;
  readOnly: boolean;
  targetWwNs: string[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlexVolume {
  driver: string;
  fsType: string;
  options: Record<string, string>;
  readOnly: boolean;
  secretRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Flocker {
  datasetName: string;
  datasetUuid: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GcePersistentDisk {
  fsType: string;
  partition: number;
  pdName: string;
  readOnly: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GitRepo {
  directory: string;
  repository: string;
  revision: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Glusterfs {
  endpointsName: string;
  path: string;
  readOnly: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_HostPath {
  path: string;
  type: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Iscsi {
  fsType: string;
  iqn: string;
  iscsiInterface: string;
  lun: number;
  readOnly: boolean;
  targetPortal: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Local {
  path: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Nfs {
  path: string;
  readOnly: boolean;
  server: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PersistentVolumeClaim {
  claimName: string;
  readOnly: boolean;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PhotonPersistentDisk {
  fsType: string;
  pdId: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMap {
  name: string;
  optional: boolean;
  items: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_Items[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_DownwardApi {
  items: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_Items[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ServiceAccountToken {
  audience: string;
  expirationSeconds: number;
  path: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources {
  configMap: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMap[];
  downwardApi: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_DownwardApi[];
  secret: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMap[];
  serviceAccountToken: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ServiceAccountToken[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected {
  defaultMode: string;
  sources: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Quobyte {
  group: string;
  readOnly: boolean;
  registry: string;
  user: string;
  volume: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Rbd {
  cephMonitors: string[];
  fsType: string;
  keyring: string;
  radosUser: string;
  rbdImage: string;
  rbdPool: string;
  readOnly: boolean;
  secretRef: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRef[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Secret {
  defaultMode: string;
  optional: boolean;
  secretName: string;
  items: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_Items[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_VsphereVolume {
  fsType: string;
  volumePath: string;
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume {
  name: string;
  awsElasticBlockStore: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AwsElasticBlockStore[];
  azureDisk: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureDisk[];
  azureFile: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureFile[];
  cephFs: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs[];
  cinder: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Cinder[];
  configMap: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap[];
  csi: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Csi[];
  downwardApi: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi[];
  emptyDir: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EmptyDir[];
  ephemeral: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral[];
  fc: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Fc[];
  flexVolume: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlexVolume[];
  flocker: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Flocker[];
  gcePersistentDisk: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GcePersistentDisk[];
  gitRepo: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GitRepo[];
  glusterfs: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Glusterfs[];
  hostPath: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_HostPath[];
  iscsi: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Iscsi[];
  local: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Local[];
  nfs: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Nfs[];
  persistentVolumeClaim: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PersistentVolumeClaim[];
  photonPersistentDisk: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PhotonPersistentDisk[];
  projected: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected[];
  quobyte: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Quobyte[];
  rbd: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Rbd[];
  secret: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Secret[];
  vsphereVolume: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_VsphereVolume[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template_Spec {
  activeDeadlineSeconds: number;
  automountServiceAccountToken: boolean;
  dnsPolicy: string;
  enableServiceLinks: boolean;
  hostIpc: boolean;
  hostNetwork: boolean;
  hostPid: boolean;
  hostname: string;
  nodeName: string;
  nodeSelector: Record<string, string>;
  priorityClassName: string;
  restartPolicy: string;
  runtimeClassName: string;
  schedulerName: string;
  serviceAccountName: string;
  shareProcessNamespace: boolean;
  subdomain: string;
  terminationGracePeriodSeconds: number;
  affinity: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity[];
  container: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container[];
  dnsConfig: JobV1_Spec_JobTemplate_Spec_Template_Spec_DnsConfig[];
  hostAliases: JobV1_Spec_JobTemplate_Spec_Template_Spec_HostAliases[];
  imagePullSecrets: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecrets[];
  initContainer: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container[];
  os: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecrets[];
  readinessGate: JobV1_Spec_JobTemplate_Spec_Template_Spec_ReadinessGate[];
  securityContext: JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext[];
  toleration: JobV1_Spec_JobTemplate_Spec_Template_Spec_Toleration[];
  topologySpreadConstraint: JobV1_Spec_JobTemplate_Spec_Template_Spec_TopologySpreadConstraint[];
  volume: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume[];
}

export interface JobV1_Spec_JobTemplate_Spec_Template {
  metadata: JobV1_Spec_JobTemplate_Spec_Template_Metadata[];
  spec: JobV1_Spec_JobTemplate_Spec_Template_Spec[];
}

export interface JobV1_Spec_JobTemplate_Spec {
  activeDeadlineSeconds: number;
  backoffLimit: number;
  backoffLimitPerIndex: number;
  completionMode: string;
  completions: number;
  manualSelector: boolean;
  maxFailedIndexes: number;
  parallelism: number;
  ttlSecondsAfterFinished: string;
  podFailurePolicy: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy[];
  selector: JobV1_Spec_JobTemplate_Spec_Selector[];
  template: JobV1_Spec_JobTemplate_Spec_Template[];
}

export interface JobV1_Spec_JobTemplate {
  metadata: JobV1_Metadata[];
  spec: JobV1_Spec_JobTemplate_Spec[];
}

export interface JobV1_Spec {
  concurrencyPolicy: string;
  failedJobsHistoryLimit: number;
  schedule: string;
  startingDeadlineSeconds: number;
  successfulJobsHistoryLimit: number;
  suspend: boolean;
  timezone: string;
  jobTemplate: JobV1_Spec_JobTemplate[];
}

export interface JobV1_Timeouts {
  delete: string;
}

const JobV1_MetadataFields: FieldMap = {
  annotations: "annotations",
  generateName: "generate_name",
  generation: "generation",
  labels: "labels",
  name: "name",
  namespace: "namespace",
  resourceVersion: "resource_version",
  uid: "uid",
};

const JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnExitCodesFields: FieldMap = {
  containerName: "container_name",
  operator: "operator",
  values: "values",
};

const JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnPodConditionFields: FieldMap = {
  status: "status",
  type: "type",
};

const JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_RuleFields: FieldMap = {
  action: "action",
  onExitCodes: {
    wireName: "on_exit_codes",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnExitCodesFields,
  },
  onPodCondition: {
    wireName: "on_pod_condition",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_Rule_OnPodConditionFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_PodFailurePolicyFields: FieldMap = {
  rule: {
    wireName: "rule",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_PodFailurePolicy_RuleFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressionsFields: FieldMap = {
  key: "key",
  operator: "operator",
  values: "values",
};

const JobV1_Spec_JobTemplate_Spec_SelectorFields: FieldMap = {
  matchLabels: "match_labels",
  matchExpressions: {
    wireName: "match_expressions",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressionsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_MetadataFields: FieldMap = {
  annotations: "annotations",
  generateName: "generate_name",
  generation: "generation",
  labels: "labels",
  name: "name",
  resourceVersion: "resource_version",
  uid: "uid",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PreferenceFields: FieldMap = {
  matchExpressions: {
    wireName: "match_expressions",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressionsFields,
  },
  matchFields: {
    wireName: "match_fields",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Selector_MatchExpressionsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecutionFields: FieldMap = {
  weight: "weight",
  preference: {
    wireName: "preference",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PreferenceFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecutionFields: FieldMap = {
  nodeSelectorTerm: {
    wireName: "node_selector_term",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PreferenceFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinityFields: FieldMap = {
  preferredDuringSchedulingIgnoredDuringExecution: {
    wireName: "preferred_during_scheduling_ignored_during_execution",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_PreferredDuringSchedulingIgnoredDuringExecutionFields,
  },
  requiredDuringSchedulingIgnoredDuringExecution: {
    wireName: "required_during_scheduling_ignored_during_execution",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinity_RequiredDuringSchedulingIgnoredDuringExecutionFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTermFields: FieldMap = {
  namespaces: "namespaces",
  topologyKey: "topology_key",
  labelSelector: {
    wireName: "label_selector",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_SelectorFields,
  },
  namespaceSelector: {
    wireName: "namespace_selector",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_SelectorFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecutionFields: FieldMap = {
  weight: "weight",
  podAffinityTerm: {
    wireName: "pod_affinity_term",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTermFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinityFields: FieldMap = {
  preferredDuringSchedulingIgnoredDuringExecution: {
    wireName: "preferred_during_scheduling_ignored_during_execution",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecutionFields,
  },
  requiredDuringSchedulingIgnoredDuringExecution: {
    wireName: "required_during_scheduling_ignored_during_execution",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinity_PreferredDuringSchedulingIgnoredDuringExecution_PodAffinityTermFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_AffinityFields: FieldMap = {
  nodeAffinity: {
    wireName: "node_affinity",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_NodeAffinityFields,
  },
  podAffinity: {
    wireName: "pod_affinity",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinityFields,
  },
  podAntiAffinity: {
    wireName: "pod_anti_affinity",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Affinity_PodAffinityFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRefFields: FieldMap = {
  key: "key",
  name: "name",
  optional: "optional",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRefFields: FieldMap = {
  apiVersion: "api_version",
  fieldPath: "field_path",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRefFields: FieldMap = {
  containerName: "container_name",
  divisor: "divisor",
  resource: "resource",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFromFields: FieldMap = {
  configMapKeyRef: {
    wireName: "config_map_key_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRefFields,
  },
  fieldRef: {
    wireName: "field_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRefFields,
  },
  resourceFieldRef: {
    wireName: "resource_field_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRefFields,
  },
  secretKeyRef: {
    wireName: "secret_key_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ConfigMapKeyRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFields: FieldMap = {
  name: "name",
  value: "value",
  valueFrom: {
    wireName: "value_from",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFromFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRefFields: FieldMap = {
  name: "name",
  optional: "optional",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFromFields: FieldMap = {
  prefix: "prefix",
  configMapRef: {
    wireName: "config_map_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRefFields,
  },
  secretRef: {
    wireName: "secret_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFrom_ConfigMapRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_ExecFields: FieldMap = {
  command: "command",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeaderFields: FieldMap = {
  name: "name",
  value: "value",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGetFields: FieldMap = {
  host: "host",
  path: "path",
  port: "port",
  scheme: "scheme",
  httpHeader: {
    wireName: "http_header",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeaderFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocketFields: FieldMap = {
  port: "port",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStartFields: FieldMap = {
  exec: {
    wireName: "exec",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_ExecFields,
  },
  httpGet: {
    wireName: "http_get",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGetFields,
  },
  tcpSocket: {
    wireName: "tcp_socket",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocketFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LifecycleFields: FieldMap = {
  postStart: {
    wireName: "post_start",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStartFields,
  },
  preStop: {
    wireName: "pre_stop",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStartFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe_GrpcFields: FieldMap = {
  port: "port",
  service: "service",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbeFields: FieldMap = {
  failureThreshold: "failure_threshold",
  initialDelaySeconds: "initial_delay_seconds",
  periodSeconds: "period_seconds",
  successThreshold: "success_threshold",
  timeoutSeconds: "timeout_seconds",
  exec: {
    wireName: "exec",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_ExecFields,
  },
  grpc: {
    wireName: "grpc",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbe_GrpcFields,
  },
  httpGet: {
    wireName: "http_get",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGetFields,
  },
  tcpSocket: {
    wireName: "tcp_socket",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_TcpSocketFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_PortFields: FieldMap = {
  containerPort: "container_port",
  hostIp: "host_ip",
  hostPort: "host_port",
  name: "name",
  protocol: "protocol",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_ResourcesFields: FieldMap = {
  limits: "limits",
  requests: "requests",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_CapabilitiesFields: FieldMap = {
  add: "add",
  drop: "drop",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptionsFields: FieldMap = {
  level: "level",
  role: "role",
  type: "type",
  user: "user",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfileFields: FieldMap = {
  localhostProfile: "localhost_profile",
  type: "type",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContextFields: FieldMap = {
  allowPrivilegeEscalation: "allow_privilege_escalation",
  privileged: "privileged",
  readOnlyRootFilesystem: "read_only_root_filesystem",
  runAsGroup: "run_as_group",
  runAsNonRoot: "run_as_non_root",
  runAsUser: "run_as_user",
  capabilities: {
    wireName: "capabilities",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_CapabilitiesFields,
  },
  seLinuxOptions: {
    wireName: "se_linux_options",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptionsFields,
  },
  seccompProfile: {
    wireName: "seccomp_profile",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfileFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeDeviceFields: FieldMap = {
  devicePath: "device_path",
  name: "name",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeMountFields: FieldMap = {
  mountPath: "mount_path",
  mountPropagation: "mount_propagation",
  name: "name",
  readOnly: "read_only",
  subPath: "sub_path",
  subPathExpr: "sub_path_expr",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_ContainerFields: FieldMap = {
  args: "args",
  command: "command",
  image: "image",
  imagePullPolicy: "image_pull_policy",
  name: "name",
  restartPolicy: "restart_policy",
  stdin: "stdin",
  stdinOnce: "stdin_once",
  terminationMessagePath: "termination_message_path",
  terminationMessagePolicy: "termination_message_policy",
  tty: "tty",
  workingDir: "working_dir",
  env: {
    wireName: "env",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFields,
  },
  envFrom: {
    wireName: "env_from",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_EnvFromFields,
  },
  lifecycle: {
    wireName: "lifecycle",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LifecycleFields,
  },
  livenessProbe: {
    wireName: "liveness_probe",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbeFields,
  },
  port: {
    wireName: "port",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_PortFields,
  },
  readinessProbe: {
    wireName: "readiness_probe",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbeFields,
  },
  resources: {
    wireName: "resources",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_ResourcesFields,
  },
  securityContext: {
    wireName: "security_context",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContextFields,
  },
  startupProbe: {
    wireName: "startup_probe",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_LivenessProbeFields,
  },
  volumeDevice: {
    wireName: "volume_device",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeDeviceFields,
  },
  volumeMount: {
    wireName: "volume_mount",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_VolumeMountFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_DnsConfigFields: FieldMap = {
  nameservers: "nameservers",
  searches: "searches",
  option: {
    wireName: "option",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeaderFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_HostAliasesFields: FieldMap = {
  hostnames: "hostnames",
  ip: "ip",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecretsFields: FieldMap = {
  name: "name",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_ReadinessGateFields: FieldMap = {
  conditionType: "condition_type",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext_WindowsOptionsFields: FieldMap = {
  gmsaCredentialSpec: "gmsa_credential_spec",
  gmsaCredentialSpecName: "gmsa_credential_spec_name",
  hostProcess: "host_process",
  runAsUsername: "run_as_username",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContextFields: FieldMap = {
  fsGroup: "fs_group",
  fsGroupChangePolicy: "fs_group_change_policy",
  runAsGroup: "run_as_group",
  runAsNonRoot: "run_as_non_root",
  runAsUser: "run_as_user",
  supplementalGroups: "supplemental_groups",
  seLinuxOptions: {
    wireName: "se_linux_options",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeLinuxOptionsFields,
  },
  seccompProfile: {
    wireName: "seccomp_profile",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_SecurityContext_SeccompProfileFields,
  },
  sysctl: {
    wireName: "sysctl",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Lifecycle_PostStart_HttpGet_HttpHeaderFields,
  },
  windowsOptions: {
    wireName: "windows_options",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContext_WindowsOptionsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_TolerationFields: FieldMap = {
  effect: "effect",
  key: "key",
  operator: "operator",
  tolerationSeconds: "toleration_seconds",
  value: "value",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_TopologySpreadConstraintFields: FieldMap = {
  matchLabelKeys: "match_label_keys",
  maxSkew: "max_skew",
  minDomains: "min_domains",
  nodeAffinityPolicy: "node_affinity_policy",
  nodeTaintsPolicy: "node_taints_policy",
  topologyKey: "topology_key",
  whenUnsatisfiable: "when_unsatisfiable",
  labelSelector: {
    wireName: "label_selector",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_SelectorFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AwsElasticBlockStoreFields: FieldMap = {
  fsType: "fs_type",
  partition: "partition",
  readOnly: "read_only",
  volumeId: "volume_id",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureDiskFields: FieldMap = {
  cachingMode: "caching_mode",
  dataDiskUri: "data_disk_uri",
  diskName: "disk_name",
  fsType: "fs_type",
  kind: "kind",
  readOnly: "read_only",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureFileFields: FieldMap = {
  readOnly: "read_only",
  secretName: "secret_name",
  secretNamespace: "secret_namespace",
  shareName: "share_name",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRefFields: FieldMap = {
  name: "name",
  namespace: "namespace",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFsFields: FieldMap = {
  monitors: "monitors",
  path: "path",
  readOnly: "read_only",
  secretFile: "secret_file",
  user: "user",
  secretRef: {
    wireName: "secret_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CinderFields: FieldMap = {
  fsType: "fs_type",
  readOnly: "read_only",
  volumeId: "volume_id",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_ItemsFields: FieldMap = {
  key: "key",
  mode: "mode",
  path: "path",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMapFields: FieldMap = {
  defaultMode: "default_mode",
  name: "name",
  optional: "optional",
  items: {
    wireName: "items",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_ItemsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CsiFields: FieldMap = {
  driver: "driver",
  fsType: "fs_type",
  readOnly: "read_only",
  volumeAttributes: "volume_attributes",
  nodePublishSecretRef: {
    wireName: "node_publish_secret_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecretsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_ItemsFields: FieldMap = {
  mode: "mode",
  path: "path",
  fieldRef: {
    wireName: "field_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_FieldRefFields,
  },
  resourceFieldRef: {
    wireName: "resource_field_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_Env_ValueFrom_ResourceFieldRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApiFields: FieldMap = {
  defaultMode: "default_mode",
  items: {
    wireName: "items",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_ItemsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EmptyDirFields: FieldMap = {
  medium: "medium",
  sizeLimit: "size_limit",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_MetadataFields: FieldMap = {
  annotations: "annotations",
  labels: "labels",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_SpecFields: FieldMap = {
  accessModes: "access_modes",
  storageClassName: "storage_class_name",
  volumeMode: "volume_mode",
  volumeName: "volume_name",
  resources: {
    wireName: "resources",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Container_ResourcesFields,
  },
  selector: {
    wireName: "selector",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_SelectorFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplateFields: FieldMap = {
  metadata: {
    wireName: "metadata",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_MetadataFields,
  },
  spec: {
    wireName: "spec",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplate_SpecFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EphemeralFields: FieldMap = {
  volumeClaimTemplate: {
    wireName: "volume_claim_template",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Ephemeral_VolumeClaimTemplateFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FcFields: FieldMap = {
  fsType: "fs_type",
  lun: "lun",
  readOnly: "read_only",
  targetWwNs: "target_ww_ns",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlexVolumeFields: FieldMap = {
  driver: "driver",
  fsType: "fs_type",
  options: "options",
  readOnly: "read_only",
  secretRef: {
    wireName: "secret_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlockerFields: FieldMap = {
  datasetName: "dataset_name",
  datasetUuid: "dataset_uuid",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GcePersistentDiskFields: FieldMap = {
  fsType: "fs_type",
  partition: "partition",
  pdName: "pd_name",
  readOnly: "read_only",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GitRepoFields: FieldMap = {
  directory: "directory",
  repository: "repository",
  revision: "revision",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GlusterfsFields: FieldMap = {
  endpointsName: "endpoints_name",
  path: "path",
  readOnly: "read_only",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_HostPathFields: FieldMap = {
  path: "path",
  type: "type",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_IscsiFields: FieldMap = {
  fsType: "fs_type",
  iqn: "iqn",
  iscsiInterface: "iscsi_interface",
  lun: "lun",
  readOnly: "read_only",
  targetPortal: "target_portal",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_LocalFields: FieldMap = {
  path: "path",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_NfsFields: FieldMap = {
  path: "path",
  readOnly: "read_only",
  server: "server",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PersistentVolumeClaimFields: FieldMap = {
  claimName: "claim_name",
  readOnly: "read_only",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PhotonPersistentDiskFields: FieldMap = {
  fsType: "fs_type",
  pdId: "pd_id",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMapFields: FieldMap = {
  name: "name",
  optional: "optional",
  items: {
    wireName: "items",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_ItemsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_DownwardApiFields: FieldMap = {
  items: {
    wireName: "items",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApi_ItemsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ServiceAccountTokenFields: FieldMap = {
  audience: "audience",
  expirationSeconds: "expiration_seconds",
  path: "path",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_SourcesFields: FieldMap = {
  configMap: {
    wireName: "config_map",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMapFields,
  },
  downwardApi: {
    wireName: "downward_api",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_DownwardApiFields,
  },
  secret: {
    wireName: "secret",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ConfigMapFields,
  },
  serviceAccountToken: {
    wireName: "service_account_token",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_Sources_ServiceAccountTokenFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ProjectedFields: FieldMap = {
  defaultMode: "default_mode",
  sources: {
    wireName: "sources",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_Projected_SourcesFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_QuobyteFields: FieldMap = {
  group: "group",
  readOnly: "read_only",
  registry: "registry",
  user: "user",
  volume: "volume",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_RbdFields: FieldMap = {
  cephMonitors: "ceph_monitors",
  fsType: "fs_type",
  keyring: "keyring",
  radosUser: "rados_user",
  rbdImage: "rbd_image",
  rbdPool: "rbd_pool",
  readOnly: "read_only",
  secretRef: {
    wireName: "secret_ref",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFs_SecretRefFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_SecretFields: FieldMap = {
  defaultMode: "default_mode",
  optional: "optional",
  secretName: "secret_name",
  items: {
    wireName: "items",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMap_ItemsFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_VsphereVolumeFields: FieldMap = {
  fsType: "fs_type",
  volumePath: "volume_path",
};

const JobV1_Spec_JobTemplate_Spec_Template_Spec_VolumeFields: FieldMap = {
  name: "name",
  awsElasticBlockStore: {
    wireName: "aws_elastic_block_store",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AwsElasticBlockStoreFields,
  },
  azureDisk: {
    wireName: "azure_disk",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureDiskFields,
  },
  azureFile: {
    wireName: "azure_file",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_AzureFileFields,
  },
  cephFs: {
    wireName: "ceph_fs",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CephFsFields,
  },
  cinder: {
    wireName: "cinder",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CinderFields,
  },
  configMap: {
    wireName: "config_map",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ConfigMapFields,
  },
  csi: {
    wireName: "csi",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_CsiFields,
  },
  downwardApi: {
    wireName: "downward_api",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_DownwardApiFields,
  },
  emptyDir: {
    wireName: "empty_dir",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EmptyDirFields,
  },
  ephemeral: {
    wireName: "ephemeral",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_EphemeralFields,
  },
  fc: {
    wireName: "fc",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FcFields,
  },
  flexVolume: {
    wireName: "flex_volume",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlexVolumeFields,
  },
  flocker: {
    wireName: "flocker",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_FlockerFields,
  },
  gcePersistentDisk: {
    wireName: "gce_persistent_disk",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GcePersistentDiskFields,
  },
  gitRepo: {
    wireName: "git_repo",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GitRepoFields,
  },
  glusterfs: {
    wireName: "glusterfs",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_GlusterfsFields,
  },
  hostPath: {
    wireName: "host_path",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_HostPathFields,
  },
  iscsi: {
    wireName: "iscsi",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_IscsiFields,
  },
  local: {
    wireName: "local",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_LocalFields,
  },
  nfs: {
    wireName: "nfs",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_NfsFields,
  },
  persistentVolumeClaim: {
    wireName: "persistent_volume_claim",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PersistentVolumeClaimFields,
  },
  photonPersistentDisk: {
    wireName: "photon_persistent_disk",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_PhotonPersistentDiskFields,
  },
  projected: {
    wireName: "projected",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_ProjectedFields,
  },
  quobyte: {
    wireName: "quobyte",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_QuobyteFields,
  },
  rbd: {
    wireName: "rbd",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_RbdFields,
  },
  secret: {
    wireName: "secret",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_SecretFields,
  },
  vsphereVolume: {
    wireName: "vsphere_volume",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_Volume_VsphereVolumeFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_Template_SpecFields: FieldMap = {
  activeDeadlineSeconds: "active_deadline_seconds",
  automountServiceAccountToken: "automount_service_account_token",
  dnsPolicy: "dns_policy",
  enableServiceLinks: "enable_service_links",
  hostIpc: "host_ipc",
  hostNetwork: "host_network",
  hostPid: "host_pid",
  hostname: "hostname",
  nodeName: "node_name",
  nodeSelector: "node_selector",
  priorityClassName: "priority_class_name",
  restartPolicy: "restart_policy",
  runtimeClassName: "runtime_class_name",
  schedulerName: "scheduler_name",
  serviceAccountName: "service_account_name",
  shareProcessNamespace: "share_process_namespace",
  subdomain: "subdomain",
  terminationGracePeriodSeconds: "termination_grace_period_seconds",
  affinity: {
    wireName: "affinity",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_AffinityFields,
  },
  container: {
    wireName: "container",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ContainerFields,
  },
  dnsConfig: {
    wireName: "dns_config",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_DnsConfigFields,
  },
  hostAliases: {
    wireName: "host_aliases",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_HostAliasesFields,
  },
  imagePullSecrets: {
    wireName: "image_pull_secrets",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecretsFields,
  },
  initContainer: {
    wireName: "init_container",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ContainerFields,
  },
  os: {
    wireName: "os",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ImagePullSecretsFields,
  },
  readinessGate: {
    wireName: "readiness_gate",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_ReadinessGateFields,
  },
  securityContext: {
    wireName: "security_context",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_SecurityContextFields,
  },
  toleration: {
    wireName: "toleration",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_TolerationFields,
  },
  topologySpreadConstraint: {
    wireName: "topology_spread_constraint",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_TopologySpreadConstraintFields,
  },
  volume: {
    wireName: "volume",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_Spec_VolumeFields,
  },
};

const JobV1_Spec_JobTemplate_Spec_TemplateFields: FieldMap = {
  metadata: {
    wireName: "metadata",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_MetadataFields,
  },
  spec: {
    wireName: "spec",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_Template_SpecFields,
  },
};

const JobV1_Spec_JobTemplate_SpecFields: FieldMap = {
  activeDeadlineSeconds: "active_deadline_seconds",
  backoffLimit: "backoff_limit",
  backoffLimitPerIndex: "backoff_limit_per_index",
  completionMode: "completion_mode",
  completions: "completions",
  manualSelector: "manual_selector",
  maxFailedIndexes: "max_failed_indexes",
  parallelism: "parallelism",
  ttlSecondsAfterFinished: "ttl_seconds_after_finished",
  podFailurePolicy: {
    wireName: "pod_failure_policy",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_PodFailurePolicyFields,
  },
  selector: {
    wireName: "selector",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_SelectorFields,
  },
  template: {
    wireName: "template",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_Spec_TemplateFields,
  },
};

const JobV1_Spec_JobTemplateFields: FieldMap = {
  metadata: {
    wireName: "metadata",
    kind: "list",
    fields: JobV1_MetadataFields,
  },
  spec: {
    wireName: "spec",
    kind: "list",
    fields: JobV1_Spec_JobTemplate_SpecFields,
  },
};

const JobV1_SpecFields: FieldMap = {
  concurrencyPolicy: "concurrency_policy",
  failedJobsHistoryLimit: "failed_jobs_history_limit",
  schedule: "schedule",
  startingDeadlineSeconds: "starting_deadline_seconds",
  successfulJobsHistoryLimit: "successful_jobs_history_limit",
  suspend: "suspend",
  timezone: "timezone",
  jobTemplate: {
    wireName: "job_template",
    kind: "list",
    fields: JobV1_Spec_JobTemplateFields,
  },
};

const JobV1_TimeoutsFields: FieldMap = {
  delete: "delete",
};

export interface JobV1Config {
  id?: string | Computed<string>;
  metadata?: JobV1_Metadata[] | Computed<JobV1_Metadata[]>;
  spec?: JobV1_Spec[] | Computed<JobV1_Spec[]>;
  timeouts?: JobV1_Timeouts | Computed<JobV1_Timeouts>;
}

export interface JobV1Attrs {
  id: string;
  metadata: JobV1_Metadata[];
  spec: JobV1_Spec[];
  timeouts: JobV1_Timeouts;
}

export const JobV1: ResourceBinding<JobV1Config, JobV1Attrs> = {
  wireType: "kubernetes_cron_job_v1",
  fields: {
    id: "id",
    metadata: {
      wireName: "metadata",
      kind: "list",
      fields: JobV1_MetadataFields,
    },
    spec: {
      wireName: "spec",
      kind: "list",
      fields: JobV1_SpecFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: JobV1_TimeoutsFields,
    },
  },
};
