// Code generated by `ubx sdk gen` from kubernetes_env. DO NOT EDIT.
package env

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Env_Env_ValueFrom_ConfigMapKeyRef struct {
	Key any
	Name any
	Optional any
}

type Env_Env_ValueFrom_FieldRef struct {
	ApiVersion any
	FieldPath any
}

type Env_Env_ValueFrom_ResourceFieldRef struct {
	ContainerName any
	Divisor any
	Resource any
}

type Env_Env_ValueFrom struct {
	ConfigMapKeyRef any
	FieldRef any
	ResourceFieldRef any
	SecretKeyRef any
}

type Env_Env struct {
	Name any
	Value any
	ValueFrom any
}

type Env_Metadata struct {
	Name any
	Namespace any
}

var Env_Env_ValueFrom_ConfigMapKeyRefFields = ubx.FieldMap{
		"Key": ubx.FieldSpec{WireName: "key"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Optional": ubx.FieldSpec{WireName: "optional"},
	}

var Env_Env_ValueFrom_FieldRefFields = ubx.FieldMap{
		"ApiVersion": ubx.FieldSpec{WireName: "api_version"},
		"FieldPath": ubx.FieldSpec{WireName: "field_path"},
	}

var Env_Env_ValueFrom_ResourceFieldRefFields = ubx.FieldMap{
		"ContainerName": ubx.FieldSpec{WireName: "container_name"},
		"Divisor": ubx.FieldSpec{WireName: "divisor"},
		"Resource": ubx.FieldSpec{WireName: "resource"},
	}

var Env_Env_ValueFromFields = ubx.FieldMap{
		"ConfigMapKeyRef": ubx.FieldSpec{
			WireName: "config_map_key_ref",
			Kind: "list",
			Fields: Env_Env_ValueFrom_ConfigMapKeyRefFields,
		},
		"FieldRef": ubx.FieldSpec{
			WireName: "field_ref",
			Kind: "list",
			Fields: Env_Env_ValueFrom_FieldRefFields,
		},
		"ResourceFieldRef": ubx.FieldSpec{
			WireName: "resource_field_ref",
			Kind: "list",
			Fields: Env_Env_ValueFrom_ResourceFieldRefFields,
		},
		"SecretKeyRef": ubx.FieldSpec{
			WireName: "secret_key_ref",
			Kind: "list",
			Fields: Env_Env_ValueFrom_ConfigMapKeyRefFields,
		},
	}

var Env_EnvFields = ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"Value": ubx.FieldSpec{WireName: "value"},
		"ValueFrom": ubx.FieldSpec{
			WireName: "value_from",
			Kind: "list",
			Fields: Env_Env_ValueFromFields,
		},
	}

var Env_MetadataFields = ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"Namespace": ubx.FieldSpec{WireName: "namespace"},
	}

type EnvConfig struct {
	ApiVersion any
	Container any
	FieldManager any
	Force any
	Id any
	InitContainer any
	Kind any
	Env any
	Metadata any
}

var Env = ubx.ResourceBinding{
	WireType: "kubernetes_env",
	Fields: ubx.FieldMap{
		"ApiVersion": ubx.FieldSpec{WireName: "api_version"},
		"Container": ubx.FieldSpec{WireName: "container"},
		"FieldManager": ubx.FieldSpec{WireName: "field_manager"},
		"Force": ubx.FieldSpec{WireName: "force"},
		"Id": ubx.FieldSpec{WireName: "id"},
		"InitContainer": ubx.FieldSpec{WireName: "init_container"},
		"Kind": ubx.FieldSpec{WireName: "kind"},
		"Env": ubx.FieldSpec{
			WireName: "env",
			Kind: "list",
			Fields: Env_EnvFields,
		},
		"Metadata": ubx.FieldSpec{
			WireName: "metadata",
			Kind: "list",
			Fields: Env_MetadataFields,
		},
	},
}
