// Code generated by `ubx sdk gen` from kubernetes_ingress_class. DO NOT EDIT.
package ingress

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Class_Metadata struct {
	Annotations any
	GenerateName any
	Generation any
	Labels any
	Name any
	ResourceVersion any
	Uid any
}

type Class_Spec_Parameters struct {
	ApiGroup any
	Kind any
	Name any
	Namespace any
	Scope any
}

type Class_Spec struct {
	Controller any
	Parameters any
}

var Class_MetadataFields = ubx.FieldMap{
		"Annotations": ubx.FieldSpec{WireName: "annotations"},
		"GenerateName": ubx.FieldSpec{WireName: "generate_name"},
		"Generation": ubx.FieldSpec{WireName: "generation"},
		"Labels": ubx.FieldSpec{WireName: "labels"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ResourceVersion": ubx.FieldSpec{WireName: "resource_version"},
		"Uid": ubx.FieldSpec{WireName: "uid"},
	}

var Class_Spec_ParametersFields = ubx.FieldMap{
		"ApiGroup": ubx.FieldSpec{WireName: "api_group"},
		"Kind": ubx.FieldSpec{WireName: "kind"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Namespace": ubx.FieldSpec{WireName: "namespace"},
		"Scope": ubx.FieldSpec{WireName: "scope"},
	}

var Class_SpecFields = ubx.FieldMap{
		"Controller": ubx.FieldSpec{WireName: "controller"},
		"Parameters": ubx.FieldSpec{
			WireName: "parameters",
			Kind: "list",
			Fields: Class_Spec_ParametersFields,
		},
	}

type ClassConfig struct {
	Id any
	Metadata any
	Spec any
}

var Class = ubx.ResourceBinding{
	WireType: "kubernetes_ingress_class",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
		"Metadata": ubx.FieldSpec{
			WireName: "metadata",
			Kind: "list",
			Fields: Class_MetadataFields,
		},
		"Spec": ubx.FieldSpec{
			WireName: "spec",
			Kind: "list",
			Fields: Class_SpecFields,
		},
	},
}
